### ISSUE TITLE
ossec-authd doesn't use password specified in agent_auth_password

### ISSUE THREAD

**Issue by TravellingGuy** [wazuh/wazuh-puppet#105]
When a password is specified in the `agent_auth_password` parameter, the ossec-authd daemon still starts up not requiring a password:
`ossec-authd: INFO: Accepting connections on port 1515. No password required.`

When a password is specified, the ossec.conf also needs to be updated with this:
```
<auth>
  <use_password>yes</use_password>
</auth>
```
to tell it to start up using the password.

Right now I'm working around it by using `concat::fragment` to add that bit to the ossec.conf, like this:
```
  # Insert the <auth> section of the ossec.conf, that tells ossec-authd to use the password
  # specified in the configuration.
  concat::fragment { 'auth_section':
    target => 'ossec.conf',
    order => 50,
    content => template('profiles/wazuh/ossec_conf_auth_section.erb'),
  }
```

**Comment by LuisGi93** [comment]
Hi @TravellingGuy,
the PR https://github.com/wazuh/wazuh-puppet/pull/103 solved this issue. It is posible to enable the ossec-authd password when deploying the manager using a manifest like the following:

```puppet
node "change_me_manager" {
   class { 'wazuh::server':
     ossec_auth_use_password => true,
     agent_auth_password => 'change_me_password'
   }

}

```

Regards.
