### ISSUE TITLE
Cluster Mode Register and send log

### ISSUE THREAD

**Issue by magnussen7** [wazuh/wazuh-puppet#110]
Hi,
In a cluster mode it's impossible to register an agent to the master and send log to a worker through the puppet module. It would be great if the master could send a worker ip address to the agent automatically or separate master ip and worker ip in the puppet module.

**Comment by JPLachance** [comment]
Hello!

I just noticed the same thing, but there might be a workaround.

In the [client.pp](https://github.com/wazuh/wazuh-puppet/blob/master/manifests/client.pp#L162), the agent `authd` registration command is using the `ossec_server_address` or the `ossec_server_ip`. 

Then, if we look at the [wazuh_agent.conf.erb](https://github.com/wazuh/wazuh-puppet/blob/master/templates/wazuh_agent.conf.erb#L10) file, the template is setting the `<server>` `<address>` to ` @ossec_server_ip`, then `@ossec_server_hostname`, then `@wazuh_manager_address`. I think when we give multiple addresses to the Wazuh agent, only the last one is used.

Knowing that, if we set `ossec_server_address` to the Wazuh master load balancer address and set `wazuh_manager_address` to the Wazuh workers load balancer address, the registration with `authd` will be done to the master and the agents will send their logs to the workers.

I think that's how we are supposed to use it, the documentation is just not explaining it 😄

**Comment by manuasir** [comment]
Hi, @JPLachance and @magnussen7 

We are about to approach this soon, stay tuned here. We will also make sure that the documentation is properly updated. Thanks for your collaboration.

Cheers

**Comment by jm404** [comment]
Hi, team,

In order to add this feature for Wazuh Puppet there are some task that must be done.

#### Tasks

- [ ] Adapt the code to fit different IP's

- [ ] Test new changes in a Wazuh Cluster

- [ ] Update documentation

Best regards,

Jose

**Comment by manuasir** [comment]
Done here #136
