### ISSUE TITLE
Test the Wazuh Puppet deployment. Verify it installs the 4.9.0-2 package.

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-puppet#1104]
related: https://github.com/wazuh/wazuh-automation/issues/1830

## Description

Due to a bug found after the 4.9.0, a new revision (2) for the wazuh-dashboard will be released. We will need to perform some tests with Wazuh installation assistant to ensure that the correct package of Wazuh dashboard is installed.

## Test

- [ ] Test Single Node installation in DEB distribution 
- [ ] Test Single Node installation in RPM distribution

**Comment by teddytpc1** [comment]
The Puppet installation alternative uses the same strategy as Ansible to deploy for APT and RPM. So, testing this deployment is not required as the test for Ansible passed:
- Related issue: https://github.com/wazuh/wazuh-ansible/issues/1401
