### ISSUE TITLE
Strange option in the Puppet documentation.

### ISSUE THREAD

**Issue by JaoChaos** [wazuh/wazuh-puppet#111]
Hi team,

![imagen](https://user-images.githubusercontent.com/16852482/53876320-d3dd7c00-4006-11e9-8c1a-96297d56d0f5.png)

That "here" option is very strange.

What does it mean, to use the option `here` or to use that section?

Regards,

Juan Anaya Ortiz.

**Comment by LuisGi93** [comment]
Hi @JaoChaos ,
you are right, some explanations are missing. It refers to use the variable [ossec_scanpaths](https://github.com/wazuh/wazuh-puppet/blob/master/manifests/server.pp#L17) at the manifest to change the directories that are going to be checked. If we dont specify nothing at the manifest by default it will monitor  `/etc`, `/usr/bin`, `/usr/sbin`:
<img src="https://user-images.githubusercontent.com/17405573/54212740-9d5ea000-44e3-11e9-94a0-a042c07ce66b.png" width="400" height="100">
![image](https://user-images.githubusercontent.com/17405573/54212800-abacbc00-44e3-11e9-838d-87e5e11b901d.png)

If for example we wanted to also check `/usr/local/sbin` we can overwrite the default values of this variable at our manifest:

![image](https://user-images.githubusercontent.com/17405573/54213764-3f32bc80-44e5-11e9-95c1-a09106680643.png)
![image](https://user-images.githubusercontent.com/17405573/54213170-44433c00-44e4-11e9-835b-165cd3ec0853.png)



 When we build a puppet manifest it is possible to use this variable

**Comment by JaoChaos** [comment]
Thanks for the explanation @LuisGi93 :+1:
