### ISSUE TITLE
Base url missing when deploying at Amazon Linux.

### ISSUE THREAD

**Issue by LuisGi93** [wazuh/wazuh-puppet#115]
Right now when a Wazuh agent or manager is deployed in Amazon Linux the following error will happen:
```
Error: Execution of '/bin/yum -e 0 -y install inotify-tools' returned 1: Loaded plugins: langpacks, priorities, update-motd
.
.
 One of the configured repositories failed (Unknown),
Cannot find a valid baseurl for repo: epel
```

**Comment by jm404** [comment]
Hello team,

As part of the new release, `inotify-tools` is being tested to guarantee that `syscheck` operates correctly under different OS's.

I will update as soon as possible with the changes / verifications about this library and it's installation.

Also, you can follow-up changes and new features about the new release in: [Release 3.9.1_7.1.0](https://github.com/wazuh/wazuh-puppet/issues/123)

Best Regards,

Jose

**Comment by manuasir** [comment]
Done here #128
