### ISSUE TITLE
wazuh Agent is not synchronized

### ISSUE THREAD

**Issue by ossecowner** [wazuh/wazuh-puppet#117]
I installed wazuh and my wazuh agent has connected to the server and is active.I did Centralized configurationof from link:
(https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html)
 but when I write (#/var/ossec/bin/agent_groups -S -i 001)
it say: (Agent '001' is not synchronized.)
I dont have error in my log file.
and my config file is ok.
please help me, why they don't sync?

**Comment by ossecowner** [comment]
Does not anyone know؟

**Comment by manuasir** [comment]
Hello @ossecowner ,

I will try to reproduce this behavior. Could you please provide further information about your case?
It'd be helpful if you could tell me which version of Wazuh are you currently using. Also, can you please paste your `agent.conf` content here? Remember to hide any sensitive data that may exist in it before. Sometimes the synchronizing process takes a while, did you test the validation of the `agent.conf` using the `/var/ossec/bin/verify-agent-conf` binary?

Cheers

**Comment by ossecowner** [comment]
Dear Cheers ;
thanks for your Response.
I'm using  Wazuh v3.8.2 with Basic license.

my agent.conf in /var/ossec/etc/shared/default/agent.conf contains only:
<agent_config os="Linux">
    <localfile>
        <location>/var/log/linux.log</location>
        <log_format>syslog</log_format>
    </localfile>
</agent_config>

 and the result of /var/ossec/bin/verify-agent-conf is:
verify-agent-conf: Verifying [/var/ossec/etc/shared/default/agent.conf]
verify-agent-conf: OK

**Comment by ossecowner** [comment]
in my ossec.conf in agent :
  `<client>`
    `<server>`
     ` <address>172.20.2.168</address>`
     ` <port>1514</port>`
      `<protocol>udp</protocol>`
    `</server>`
    `<config-profile>centos, centos7</config-profile>`
    `<notify_time>10</notify_time>`
    `<time-reconnect>60</time-reconnect>`
    `<auto_restart>yes</auto_restart>`
    `<crypto_method>aes</crypto_method>`
  `</client>`

**Comment by manuasir** [comment]
Hi @ossecowner ,

Thanks for the information. We're investigating this, I'll let you know when we get something.

Regards

**Comment by manuasir** [comment]
We tried the following scenario in our lab and we were not able to reproduce your case, let me know if I left something:

- Wazuh Manager v3.8.2 CentOS7
- Wazuh Agent v3.8.2 CentOS7
- First we ensured that the agent is correctly connected to the manager via API:
```
$ curl "http://localhost:55000/agents?select=name,ip,status&pretty" -u foo:bar
```
_Note: change foo:bar by your API credentials and localhost by your Manager IP_

It should return something like this:
```
{
   "error": 0,
   "data": {
      "totalItems": 2,
      "items": [
         {
            "status": "Active",
            "ip": "127.0.0.1",
            "name": "manager",
            "id": "000"
         },
         {
            "status": "Active",
            "ip": "172.16.1.7",
            "name": "simple-ag",
            "id": "001"
         }
  ]
}
```
- Once we already ensured that the agent is perfectly connected, we edited the `/var/ossec/etc/shared/default/agent.conf` file with this content:

```
<agent_config os="Linux">
<localfile>
<location> /var/log/linux.log </location>
<log_format>syslog</log_format>
</localfile>
</agent_config>
```
- Finally, we checked that the content is being pushed to the agent.
In the agent:
```
cat /var/ossec/etc/shared/agent.conf
```
It should have the content of the `agent.conf` configured on the manager shared `default` folder.
This command may takes some time until it returns the synchronization confirmation:

```
/var/ossec/bin/agent_groups -S -i 001
Agent '001' is synchronized. 
```

Let me know if your problem persists after following those steps.

Regards

**Comment by ossecowner** [comment]
`wazuh-agent-3.8.2-1.el5.x86_64.rpm`


> [root@hids ~]# curl "http://localhost:55000/agents?select=name,ip,status&pretty" -u x:x
{
   "error": 0,
   "data": {
      "totalItems": 2,
      "items": [
         {
            "status": "Active",
            "ip": "127.0.0.1",
            "name": "hids.socib.co",
            "id": "000"
         },
         {
            "status": "Active",
            "ip": "192.168.1.11",
            "name": "test2",
            "id": "002"
         }
      ]
   }
}

`/var/ossec/etc/shared/default/agent.conf`
> <agent_config os="Linux">
    <localfile>
        <location>/var/log/linux.log</location>
        <log_format>syslog</log_format>
    </localfile>
</agent_config>

`in agent,Ido'nt have agent.conf `:

> [root@localhost ~]# cd /var/ossec/etc/shared/
[root@localhost shared]# ls
cis_apache2224_rcl.txt   
 cis_win2012r2_domainL2_rcl.txt
cis_debian_linux_rcl.txt   
 cis_win2012r2_memberL1_rcl.txt
cis_mysql5-6_community_rcl.txt 
cis_win2012r2_memberL2_rcl.txt
cis_mysql5-6_enterprise_rcl.txt 
 merged.mg
cis_rhel5_linux_rcl.txt  
 rootkit_files.txt
cis_rhel6_linux_rcl.txt   
 rootkit_trojans.txt
cis_rhel7_linux_rcl.txt 
 system_audit_rcl.txt
cis_rhel_linux_rcl.txt  
system_audit_ssh.txt
cis_sles11_linux_rcl.txt  
win_applications_rcl.txt
cis_sles12_linux_rcl.txt  
 win_audit_rcl.txt
cis_win2012r2_domainL1_rcl.txt 
 win_malware_rcl.txt

**Comment by ossecowner** [comment]
but I have:
> [root@hids ~]# /var/ossec/bin/agent_groups -S -i 002
Agent '002' is not synchronized.
I'm confused. I do not understand what the problem is.
I dont have licence it is basic  licence, Is it relevant?

thank you very much.

**Comment by ossecowner** [comment]
My problem has been resolved. it was network problem.
thanks.

**Comment by manuasir** [comment]
Glad to hear that. Don't hesitate to open a new issue if you need it.

Regards

**Comment by nbrys** [comment]
> My problem has been resolved. it was network problem.
> thanks.

@ossecowner do you have any idea which extra ports or network change you have made?
