### ISSUE TITLE
Release 3.9.1_7.1.0

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-puppet#123]
Wazuh version: 3.9.1
Elastic version: 7.1.0

- [x] Adapt to new versions (3.9.1 - 7.1.0)
- [x] Update changelog
- [x] Update metadata.json
- [x] Update VERSION file
- [x] Tests
- [x] Publish Module on puppetforge
- [x] Tag: v3.9.1
- [x] Draft release

**Comment by jm404** [comment]
Hi team,

I've been working on the adaptation process of Puppet to Wazuh 3.9.1

### Objective

The first objective is to upgrade the *ossec.conf* file generation. In order to do this, the templates must be updated and parametrized to give the flexibility of configuration.

The following code illustrates this process:

Updated block in template:

https://github.com/wazuh/wazuh-puppet/blob/c0b37e30de7daab4f264120187b9dc310729194b/templates/wazuh_manager.conf.erb#L40-L55

Adapted default attributes:

https://github.com/wazuh/wazuh-puppet/blob/c0b37e30de7daab4f264120187b9dc310729194b/manifests/server.pp#L23-L28

The `rootcheck` block have been updated following the same process.

Further upgrades are required to adapt the `ossec.conf` files.

Best Regards,

Jose

**Comment by jm404** [comment]
Hello team,

I've made two main tasks.

### Update Manager 

I have updated Wazuh-Manager fragments

- Blocks of `localfile` are now divided for Centos and Debian families
- The `common` fragment has been removed
- Rootcheck is updated to 3.9.1 and `unixaudit` is disabled
- SCA fragments added for Centos and Debian families.

You can check details in [#92114ea](https://github.com/wazuh/wazuh-puppet/commit/92114ea205be4fa6783115b01b1148a2a6dc7c2d)

### Update Elasticsearch 

The elasticsearch repo and installation have been added. Also the defaults attributes are declared in *params_elastic*

You can check such changes in: [#176eb26](https://github.com/wazuh/wazuh-puppet/commit/176eb2687d260502f51583af73ba22a7f8570baf)

Best Regards,

Jose

**Comment by jm404** [comment]
Hi team,

I worked on implementing Filebeat, Elasticsearch and Kibana

### Filebeat

- Puppet file created and updated to 3.9.1
- Template added and parametrized

Check : [#f36be69](https://github.com/wazuh/wazuh-puppet/commit/f36be69558f012a75717150bd6a48f9b9a45b3c8)

### Elasticsearch 

- Main configuration file created and updated to 3.9.1
- Elastic repository added to `repo_elastic.pp`
- Template added and parametrized

Check: [#890fb88](https://github.com/wazuh/wazuh-puppet/commit/890fb88cdb4f18ea67caaf09943792145ac245bd)

### Kibana
- `kibana.pp` created and updated to 3.9.1
- Template added and parametrized
- Kibana app is now installed

Check: [#ac31a02](https://github.com/wazuh/wazuh-puppet/commit/ac31a02c5a6771e5e480db378934b23e2dc59b03)

Testing is required to verify such components

Best Regards,

Jose

**Comment by jm404** [comment]
Hi team,

Most of the work has been about debugging Kibana crash during installation.

### Kibana and Elastic RAM requirements

- Elasticsearch should have heap setting set to 50% of available RAM
- Kibana reaches 2.1GB of RAM on installation with Puppet.
- Minimum ram required: `5GB`

### Added hybrid blocks to give flexibility to installation.

OS dependant blocks have been added in order to properly configure installation for RedHat or Debian families.

https://github.com/wazuh/wazuh-puppet/blob/61bb27fe228f9f204d20528381f994541f9de060/templates/wazuh_manager.conf.erb#L50-L66

### Ubuntu Installation checks

- [ ] Alerts are generated and displayed properly

- [ ] Changing ossec.conf and restarting works.

- [ ] Overview graphics are correctly updated.

- [ ] No ERROR/WARNING on any log from ES, Kibana or Wazuh software.


Testing on CentOS is required and will be the following step.

Best Regards,

Jose

**Comment by jm404** [comment]
Hi team,

Most of the today's work has been spent in the following tasks:

## Improve Wazuh-API manifest

Now it supports CentOS families with no problem. The `provider` parameter has been added in order to properly manage packages with `yum` or `apt`.

Please feel free to check them at [#7aa9df9](https://github.com/wazuh/wazuh-puppet/commit/7aa9df91b9004c97812e49d46bff192f22d32021)

## Improve Elastic Repository manifest

Some problems appeared with the `repo_elastic` manifest which installs the Elastic repository in order to be able to install ELK components. 

https://github.com/wazuh/wazuh-puppet/blob/7e3721da6507d3fde5019116f340abc7b09f5b1c/manifests/repo_elastic.pp#L49-L52

Such commit is [#7e3721d](https://github.com/wazuh/wazuh-puppet/commit/7e3721da6507d3fde5019116f340abc7b09f5b1c)

Best Regards,

Jose

**Comment by jm404** [comment]
Hi team,

The biggest changes of today were:

### Make ossec.conf file flexible

The `ossec.conf` file has different blocks that need to be adapted to the running OS.

In order to make users able to choose which blocks of the configuration the want to include, `if` statements like the following  have been added to the manager.pp file.

https://github.com/wazuh/wazuh-puppet/blob/f859f879e5bd6e83b4adf54ebbe44adfc60c0f03/manifests/manager.pp#L100-L116

The localfile is now unified and adapts to OS: [#5631753](https://github.com/wazuh/wazuh-puppet/commit/5631753cf4c3967d7fc08fc53d2535d78d4e19b7)

### Server and client have been renamed

According to Wazuh nomenclature, `server.pp` and `client.pp` have been renamed to `manager.pp` and `agent.pp` respectively.

Manager associated parameters file also was renamed to `params_manager.pp`: [#f859f87](https://github.com/wazuh/wazuh-puppet/commit/f859f879e5bd6e83b4adf54ebbe44adfc60c0f03)

### Remove "export" method.

The related files to the "export" method of registration have been removed. This method used to write directly on `client.keys` which is considered insecure and could cause disruption to manager functionalities.

According to this, related files and code have been deleted: [#f77fe49](https://github.com/wazuh/wazuh-puppet/commit/f77fe496b4e290b0b3a70272c66d26f8ee7d0012)

Best Regards,

Jose

**Comment by jm404** [comment]
Hello team!

The main challenges that I faced today were:

## Unify fragments

In order to avoid having multiple fragments for same block of `ossec.conf` file, some fragments have been refactored.

- Rootcheck: [#ca11a9b](https://github.com/wazuh/wazuh-puppet/commit/ca11a9b8a67c3b84cfe43d43d065c27e047c159d)
- Cluster: [#9f64302](https://github.com/wazuh/wazuh-puppet/commit/9f643025aceab56edd7b114623ce638e3ee09452)
- SCA: [#de8bed4](https://github.com/wazuh/wazuh-puppet/commit/de8bed4fe8f7aaf62218d79028bac83ef8a22858)
- Syscheck: [#e9d31c2](https://github.com/wazuh/wazuh-puppet/commit/e9d31c2bb3abd9d08ad34ac683c1cf3ffb3c3df9)

## Update Wazuh-Agent `ossec.conf` generation

As previously done on Wazuh-Manager, blocks of if statements have been aded to give flexibility to the generation of the `ossec.conf` file in the Agent side. 

Also parameters have been moved to `wazuh::params_agent` in order to keep the main manifest of installation clean.

Example of such conditions:

https://github.com/wazuh/wazuh-puppet/blob/e271c88fc35e239e12eab21cbc524b0ddd34d106/manifests/agent.pp#L87-L113


Feel free to check such changes at: [#e271c88](https://github.com/wazuh/wazuh-puppet/commit/e271c88fc35e239e12eab21cbc524b0ddd34d106)

## Remove shell provider from exec blocks

As stated in the [official documentation] (https://puppet.com/docs/puppet/5.5/types/exec.html#exec-provider-posix) the shell provider can scape characters and cause security issues.

In order to avoid this and harden the code, `provider => shell` has been removed from the code and now it uses POSIX by default.

You can review such changes at: [#ffa8a52](https://github.com/wazuh/wazuh-puppet/commit/ffa8a521dbdd2ce5d1d3e0eb152a35ec282ef5f8)

Best Regards!

Jose

**Comment by jm404** [comment]
Hello team!

Efforts of today where spent on two main tasks

### Improve authd registration process.

An error was generated when not declaring Agent name or group. In order to fix that, the generation of the auth command for the Manager side has been fixed.

![image](https://user-images.githubusercontent.com/46649922/59617103-02024a00-9126-11e9-9436-6c2955aaaea9.png)

Now, Agent can be registered with only the `-m` parameter.

You can check such changes at: [#1e24deb](https://github.com/wazuh/wazuh-puppet/commit/1e24deb4bd30e016da1ef7381c17e5d7dc9ac5fd)

### Renaming and testing

As we manage parameters with variables, its necessary to reorder them to make the code much clearear and readable in order to ease the customization of installation.

To achieve this, renaming and reorder of variables is being made: [#c544331](https://github.com/wazuh/wazuh-puppet/commit/c544331392b08a5595a410cb46ecb7b274fe5d11) & [#4588462](https://github.com/wazuh/wazuh-puppet/commit/458846283d8b8d78c05d9674a3b0f0f1a8458d06)

Also testing of auth parameters and renaming is being made.

Best regards!

Jose

**Comment by jm404** [comment]
Hi team!

The main tasks I worked on are

### Divide command templates

The template `command.erb` is now split into `command.erb` and `default_commands`.  This allows the user to add new command blocks by using the appropriate manifest.

Check: [#b1693be](https://github.com/wazuh/wazuh-puppet/commit/b1693be16c0393b2d2bcfd7905dd774d3e54fbe5)

###  Open port for cluster

When installing a Wazuh-Cluster the open 1516 is required. Now it's possible to open it by using the variable `$ossec_cluster_enable_firewall`

https://github.com/wazuh/wazuh-puppet/blob/2e999972144489d6e37b47d4ecd5a69ec4fa000d/manifests/manager.pp#L287-L297

### Testing on CentOS

The whole installation is under testing on CentOS 7. Some of the tests that are currently passed are:

- [ ] Install Wazuh Manager & Wazuh API
- [ ] Install Elasticsearch, Filebeat, and Kibana
- [ ] Properly generate configuration files: *ossec.conf*, *elasticsearch.yml*, *kibana.yml*, *filebeat.yml*
- [ ] Install Wazuh Agent and execute registration through authd using different options.

Best regards,

Jose

**Comment by jm404** [comment]
Hi team,

I have mainly worked on the following tasks today:

## Add option to install agent but not register it.

A previously issue requested for this enhancement. I've added such feature in the `agent.pp` manifest.

Such changes are done in this commit: [#63e1a13](https://github.com/wazuh/wazuh-puppet/commit/63e1a1390edbaef4387c4397c16636514525eeaa)

## Explicitly set execution order when installing Wazuh-Agent

After the previous modifications, the order of configuring and registering the agent showed some misbehaviours. In order to guarantee the correct installation, `before` and `request` parameters have been aded.

Such changes are commited here: [#cff8073](https://github.com/wazuh/wazuh-puppet/commit/cff80733a13749d5ee9910336da450932c749b20)

## Testing

The testing on Centos 7 finished succesfully. We are currently testing the installation on other Centos based OS's.

Best regards,

Jose

**Comment by jm404** [comment]
Hi team,

Today's efforts were aimed at:

## Support Amazon-Linux 2

Said OS has been tested and some fixes have been added: [#823eeec](https://github.com/wazuh/wazuh-puppet/commit/823eeec502c4a100dc6946f25388b9d04833c105) & [#794d18a](https://github.com/wazuh/wazuh-puppet/commit/794d18ab941247e221afacd0f86a4787f3e0e99f)

Also, the $apply_template_os variable functionality has been extended like the following:
https://github.com/wazuh/wazuh-puppet/blob/794d18ab941247e221afacd0f86a4787f3e0e99f/manifests/agent.pp#L68-L78

## Remove inotify-tools

Previously `inotify-tools` was installed when *$manage_epel_repo* variable was set to true. 
Wazuh currently does not make use of such software so it's been removed from Puppet repository: [#628db1e](https://github.com/wazuh/wazuh-puppet/commit/628db1e4d5236b195ee1c50945fb6ff7553a5b23) & [#029f96b](https://github.com/wazuh/wazuh-puppet/commit/029f96b376a49e284b16407b9171beb7c80452c2)

## Updated openscap 

Openscap wodle has been updated in Ubuntu Xenial, previously was rendering properly.

https://github.com/wazuh/wazuh-puppet/blob/84f127c5ee855ac5683abda3f875bc99b2d59ae7/manifests/params_agent.pp#L209-L214 

The template has also been updated: 

## Ubuntu exec blocks fixed

The `path` parameters have been updated to fit Ubuntu and Debian and properly execute desired binaries.
[#da396a83](https://github.com/wazuh/wazuh-puppet/commit/da396a83d4c4556eb25329a51e4cb65e141e014c)

Best Regards,

Jose

**Comment by jm404** [comment]
Hi team,

Along the day I've been testing Puppet on RHEL and Debian.

Some fixes have been applied in order to support said OS.

### Fix SCA  for RHEL

The `agent.pp` and `manager.pp` now evaluate RHEL version in order to properly generate openscap wodle content.
Code on the agent:

https://github.com/wazuh/wazuh-puppet/blob/d704eafae1b1db40a5a9e1840a56f261314262d8/manifests/agent.pp#L68-L79

SCA template:

https://github.com/wazuh/wazuh-puppet/blob/7a026b2af9814cb83cb27e750b2bda143e3db316/templates/fragments/_sca.erb#L16-L48

Check at: [#d704eaf](https://github.com/wazuh/wazuh-puppet/commit/d704eafae1b1db40a5a9e1840a56f261314262d8)

## Testing

OS that have been tested are:

- [ ] Debian 7

- [ ] RHEL 7 & RHEL 6


Best Regards,

Jose

**Comment by manuasir** [comment]
Done here #128
