### ISSUE TITLE
Wazuh Manager installation on Ubuntu 14.04 generates errors related to ossec.conf

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-puppet#137]
Hi team,

It's been recently reported by @rshad that Wazuh Manager installation on Ubuntu 14.04 using Puppet generates error related to the `ossec.conf` configuration.

Best regards

Jose

**Comment by rshad** [comment]
Hi all!

We will close this issue due to that we recently stopped supporting Ubuntu 14.* .

Kr,

Rshad
