### ISSUE TITLE
Add Ubuntu to the recognized distributions in manifests

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-puppet#140]
Hi all!

When trying to deploy Wazuh components for example `manager.pp` pr `agent.pp` it fails when deploying on `Ubuntu` operating system due to the following lines:

https://github.com/wazuh/wazuh-puppet/blob/11dd4e9111200cad8f545ee7cf40f0b5ef8307f7/manifests/manager.pp#L285-L308

And to be more specific, it fails in:

https://github.com/wazuh/wazuh-puppet/blob/11dd4e9111200cad8f545ee7cf40f0b5ef8307f7/manifests/manager.pp#L297-L300

**Solution**

```
    }'Debian', 'debian', ' Ubuntu', 'ubuntu' :{
      $apply_template_os = 'debian'
      if ( $::lsbdistcodename == 'wheezy') or ($::lsbdistcodename == 'jessie'){
        $debian_additional_templates = 'yes'
```

Kr,

Rshad

**Comment by manuasir** [comment]
Done here #141
