### ISSUE TITLE
Add Filebeat module to the installation tasks

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-puppet#145]
Hi all!

Wazuh is now able to deal with a new Filebeat module which can be found [here](https://packages-dev.wazuh.com/3.x/filebeat/wazuh-filebeat-0.1.tar.gz).

To do so, we have to run the following commands:

```
curl -s https://packages-dev.wazuh.com/3.x/filebeat/wazuh-filebeat-0.1.tar.gz | tar -xvz -C /usr/share/filebeat/module
mkdir -p /usr/share/filebeat/module/wazuh
chmod 755 -R /usr/share/filebeat/module/wazuh
```

Taking into account the proper way to do it in Puppet-

Kind regards,

Rshad

**Comment by rshad** [comment]
Hi all!

The provided changes add `Filebeat` module to `Wazuh` installation using `Puppet`. We also adapted `Elasticsearch` IP so to not be assigned as `localhost` due to proven errors we got during the installation.

**Filebeat module installation**

https://github.com/wazuh/wazuh-puppet/blob/0d3f6ea1f82a6592a80caee701d1ea2e4102de22/manifests/filebeat.pp#L38-L59

**Adapting Elasticsearch IP in [Filebeat, Elasticsearch and Kibana] manifests**

https://github.com/wazuh/wazuh-puppet/blob/0d3f6ea1f82a6592a80caee701d1ea2e4102de22/manifests/filebeat.pp#L4

https://github.com/wazuh/wazuh-puppet/blob/0d3f6ea1f82a6592a80caee701d1ea2e4102de22/manifests/elasticsearch.pp#L20

https://github.com/wazuh/wazuh-puppet/blob/0d3f6ea1f82a6592a80caee701d1ea2e4102de22/manifests/kibana.pp#L9

Kind regards,

Rshad

**Comment by jm404** [comment]
Done here  #144 

Regards!
