### ISSUE TITLE
Agentless Monitoring for Cisco Switch

### ISSUE THREAD

**Issue by ossecowner** [wazuh/wazuh-puppet#152]
hi @jm404 @manuasir 

I want monitor cisco switch agentless, I configured wazuh manage like below:
`# /var/ossec/agentless/register_host.sh add root@x.x.x.x switchpassword [enablepass]`

```
<agentless>

  <type>ssh_generic_diff</type>

  <frequency>15</frequency>

  <host>root@x.x.x.x</host>

<arguments>show log</arguments>

  <state>periodic_diff</state>

</agentless
```
  ```
<remote>
    <connection>secure</connection>
    <port>1514</port>
    <protocol>tcp</protocol>
    <queue_size>131072</queue_size>
  </remote>
```

when I write:
` cat  /var/ossec/logs/ossec.log | grep "ossec-agentlessd"`
I see:
```
2019/08/31 13:51:32 ossec-agentlessd: INFO: Started (pid: 6090).
2019/08/31 13:51:34 ossec-agentlessd: ERROR: Test failed for 'ssh_generic_diff' (126). Ignoring.
2019/08/31 14:12:18 ossec-agentlessd: INFO: Started (pid: 6416).
2019/08/31 14:12:20 ossec-agentlessd: ERROR: Test failed for 'ssh_generic_diff' (126). Ignoring.
```
----why?
---- I do't know when it connect to switch how can pass from "enable" command and it's password to go to privilage mode to run "show log".
can you guide me how should I config?
---- if I want use Public key authentication instead of passwords where can I copy it into the remote device?
thank you.

**Comment by jm404** [comment]
Hi @ossecowner,

There are some check you can do to ensure your configuration is correct

- Ensure the `expect` package is installed on the Wazuh Manager, if not installed proceed to installation.

#### Using password

- If you want to use password with the Cisco router,  add the host like this:

```
/var/ossec/agentless/register_host.sh add root@example_address.com example_password enablepass
```

#### Using Public key
- If you want to use the Public key authentication ensure your Public key is generated with the user `ossec`, execute the following in the manager:

```
sudo -u ossec ssh-keygen
```

- Copy the generated Public key to the Cisco router.

- On the Manager, add the host without specifying the password:
```
/var/ossec/agentless/register_host.sh add root@example_address.com
```

#### Test configuration

- Ensure if the command you execute in the Cisco router requires privileges, if so you must specify `use_su` before the host in the configuration:

```
<agentless>

  <type>ssh_generic_diff</type>
  <frequency>15</frequency>
  <host>use_su root@x.x.x.x</host>
  <state>periodic_diff</state>
  <arguments>show log</arguments>
  

</agentless

```

- After finishing configuration, restart the Wazuh Manager

```
systemctl restart wazuh-manager
```

You should see the following in the logs:

	ossec-agentlessd: INFO: ssh_integrity_check_linux: root@example_adress.com: Starting.
	ossec-agentlessd: INFO: ssh_integrity_check_linux: root@example_adress.com: Finished.

#### References

- https://documentation.wazuh.com/3.x/user-manual/capabilities/agentless-monitoring/how-it-works.html
- https://www.ossec.net/docs/manual/agent/agentless-monitoring.html

Hope this helps to fix your problem, let me know if you need further help.

Best regards

Jose

**Comment by ossecowner** [comment]
thanks I found my problem. I run this command and installed this library and now it's ok.
`yum install expect`
