### ISSUE TITLE
EL8/CentOS 

### ISSUE THREAD

**Issue by Adspeed** [wazuh/wazuh-puppet#160]
I'm trying Wazuh on CentOS 8. It looks like things need a version bump and adjustments for EL8/CentOS 8. Thanks

[root@pm ~]# puppet module list
Warning: Module 'puppet-nodejs' (v7.0.1) fails to meet some dependencies:
  'wazuh-wazuh' (v3.10.2) requires 'puppet-nodejs' (>= 3.0.0 < 4.0.0)
Warning: Module 'puppet-selinux' (v3.0.0) fails to meet some dependencies:
  'wazuh-wazuh' (v3.10.2) requires 'puppet-selinux' (>= 0.8.0 < 3.0.0)
Warning: Module 'puppetlabs-apt' (v7.1.0) fails to meet some dependencies:
  'wazuh-wazuh' (v3.10.2) requires 'puppetlabs-apt' (>= 2.0.0 < 7.0.0)
Warning: Module 'puppetlabs-concat' (v6.1.0) fails to meet some dependencies:
  'wazuh-wazuh' (v3.10.2) requires 'puppetlabs-concat' (>= 1.0.0 < 6.0.0)
Warning: Module 'puppetlabs-firewall' (v2.1.0) fails to meet some dependencies:
  'wazuh-wazuh' (v3.10.2) requires 'puppetlabs-firewall' (>= 1.7.0 < 2.0.0)
Warning: Module 'puppetlabs-stdlib' (v6.1.0) fails to meet some dependencies:
  'wazuh-wazuh' (v3.10.2) requires 'puppetlabs-stdlib' (>= 1.0.0 < 6.0.0)

**Comment by jm404** [comment]
Hi @Adspeed,

We bumped the versions to the [metadata.json](https://github.com/wazuh/wazuh-puppet/blob/master/metadata.json) in our `master` branch. That one contains the updated dependencies version that you require. 

We plan to merge several changes from `master` to `stable` soon, until then, let me recommend you to use our [master branch](https://github.com/wazuh/wazuh-puppet/tree/master) that fulfills the dependencies you pasted in the logs.

Hope it helps,

Best regards

Jose
