### ISSUE TITLE
Package version check fails on Redhat EL5

### ISSUE THREAD

**Issue by dhouston-bt** [wazuh/wazuh-puppet#161]
Rolling 3.10.2 out, upgrading 3.8.2/3.9 agents, and seem to hit a snag on some of the older rhel5's tied to it's unique package name.

Error: Could not update: Could not find package wazuh-agent-3.10.2-1
Error: /Stage[main]/Wazuh::Agent/Package[wazuh-agent]/ensure: change from '3.10.2-1.el5' to '3.10.2-1' failed: Could not update: Could not find package wazuh-agent-3.10.2-1

Just think might need a little more logic to expect the el5 package.

Our manage_repo is false, we sync wazuh repos into our pulp.

Thanks !

**Comment by jm404** [comment]
Hi @dhouston-bt ,

The Wazuh Agent version is declared in :

https://github.com/wazuh/wazuh-puppet/blob/231e702b218ccb30bd55d4da8cf45accef3c971a/manifests/params_agent.pp#L9

Did you manage to install the Wazuh Agent package manually? Please ensure it exists and then configure the `agent_package_version`, with the exact version and any suffix the package requires.

Let me know if this fixes your situation.

Best regards,

Jose

**Comment by dhouston-bt** [comment]
Did not have to do that prior to all the changes made in May 2019 or so from 3.8 to 3.9.

We will give it a try in the next sprint or so, should be doable.  

Thank you all!
