### ISSUE TITLE
syscheck : whodata="yes" / realtime="yes" option

### ISSUE THREAD

**Issue by aderumier** [wazuh/wazuh-puppet#164]
Hi,
it seem that it's not possible anymore to define whodata="yes" on syscheck directories

I was possible before:
https://github.com/wazuh/wazuh-puppet/pull/84

Could you add the support again for theses options ?

**Comment by jm404** [comment]
Hi @aderumier,

This option was probably removed in the refactor that we did to our repo. We will check #84 and reimplement this to make users able to use this functionality.

Thanks for reporting this, it's really appreciated

Best regards,

Jse

**Comment by rshad** [comment]
Hi all!

The changes will be made to the branch: [feature-164-define-whodata](https://github.com/wazuh/wazuh-puppet/tree/feature-164-define-whodata)

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

We added all the requested changes and verified them successfully.

- Adding `whodata` and `realtime` to `syscheck` template:

https://github.com/wazuh/wazuh-puppet/blob/ef496b4cafa841f2b462c57b08bd06361ffc12ca/manifests/params_manager.pp#L162-L163

- Adding `whodata` and `realtime` to `Manager` class:

https://github.com/wazuh/wazuh-puppet/blob/ef496b4cafa841f2b462c57b08bd06361ffc12ca/manifests/manager.pp#L159-L160

- Adding the needed tasks to `Manager` class. Those are:

- - Installing `auditd` and ensure its service is running:
https://github.com/wazuh/wazuh-puppet/blob/ef496b4cafa841f2b462c57b08bd06361ffc12ca/manifests/manager.pp#L226-L234

- -  Make sure `wazuh-fmi` rule is added to `audit` rules:

https://github.com/wazuh/wazuh-puppet/blob/ef496b4cafa841f2b462c57b08bd06361ffc12ca/manifests/manager.pp#L530-L536

- `Note`: `Audit` can't be installed on Docker Containers with Event Collector role as mentioned in this [discussion](https://stackoverflow.com/questions/53311314/error-running-auditd-inside-centos-docker-container-unable-to-set-initial-audi/53311613#53311613):

> At the moment, auditd can be used inside a container only for aggregating logs from other systems. It cannot be used to get events relevant to the cotainer or the host OS. If you want to aggregate only, then set local_events=no in auditd.conf.
Container support is still under development.

** Pending testing on `Centos`

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

The changes were applied for both manager and agent configurations.

Kr,

Rshad
