### ISSUE TITLE
agent: service not reloaded on config change

### ISSUE THREAD

**Issue by aderumier** [wazuh/wazuh-puppet#165]
Hi,

It seem that agent service is not reloaded on config change.

Maybe simply add a notify on service in agent.pp concat::fragment   ?

**Comment by jm404** [comment]
Hi @aderumier,

The Wazuh Agent doesn't start automatically after getting installed so in clean installations it will be configured and then started.

Reviewing the code I noticed what you probably was pointing out, the Agent is not explicitly restarted which is already installed Agents could modify the config but don't restart the Agent.

Tasks that must be done to fix this are:

- [ ] Implement an explicit restart on config change

- [ ] Verify installation is correct on clean machines (no previous Agent installed)

- [ ] Verify that on already installed Agents, it changes the config and restarts the Agent

We will deeply review it and implement the required changes.

Thanks for your reporting this, it's really valuable for us.

Best regards,

Jose

**Comment by aderumier** [comment]
Just tested this, seem to works fine

https://github.com/wazuh/wazuh-puppet/pull/166
