### ISSUE TITLE
Puppet installation fails on Amazon Linux OS

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-puppet#168]
**Wazuh version:** 3.10.2

**Elastic version:** 7.3.2

**Environment:**
EC2 instances with Amazon Linux 2

**Is this a bug report or a feature requests?:**
Bug report

**What is the current behavior?**
Installation is failing due to undefined `wodle_openscap_content`:

https://github.com/wazuh/wazuh-puppet/blob/231e702b218ccb30bd55d4da8cf45accef3c971a/manifests/params_agent.pp#L264-L271

**What is the motivation/use case for changing the behavior?**
Fix installation by setting this variable to default configuration of Wazuh Agent or Manager.

**Description**: 

Hi all,

As described below, the installation is failing on Amazon Linux due to variable `wodle_openscap_content` being null for Amazon OS's. This causes the template for `openscap` to fail rendering and abort the execution.

### Tasks

- [x] Fix error by setting the variable to an appropiate value or avoid the rendering

- [x] Test the fix on Amazon Linux 2

Best regards

Jose

**Comment by jm404** [comment]
### Fix Amazon Linux Openscap error

The default installation of a Wazuh Manager in 3.10.2 shows the following configuration for Openscap

```
  <wodle name="open-scap">
    <disabled>yes</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>
```

Adding a conditional to the OpenSCAP template fix the error:

```
  <wodle name="open-scap">
    <disabled>yes</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>
  
  <%- if not @wodle_openscap_content.nil? -%>
    <%- @wodle_openscap_content.each do |path, value| -%>
    <content type="<%= value['type'] %>" path="<%= path %>">
      <%- if value['profiles'] then -%>
        <%- value['profiles'].each do |profile| -%>
          <profile><%= profile %></profile>
        <%- end -%>
      <%- end -%>
    </content>
    <%- end -%>
  <%- end -%>
  </wodle>
```
  
Best regards

Jose

**Comment by rshad** [comment]
Working branch: [fix-168-openscap-amazon](https://github.com/wazuh/wazuh-puppet/tree/fix-168-openscap-amazon).

**Comment by rshad** [comment]
Hi all!

The changes were applied and verified.

**1. Add condition to check if open-scap content is defined or not:**

https://github.com/wazuh/wazuh-puppet/blob/5fef8be6f732f6595d2d992c7dd98c7ef40ea105/templates/fragments/_wodle_openscap.erb#L16-L27

**2. Solving error:**

```
Error: Evaluation Error: Error while evaluating a Function Call, This ossec module has not been tested on your distribution (file: /tmp/kitchen/modules/wazuh/manifests/agent.pp, line: 259, column: 13) on node agent00_amazo59, column: 13) on node agent00_amazon
(edited)
```

This error was resolved by changing the block with which the _**os:family**_ is checked in the agent manifest, by making it check the **_operatingsystem_ .** instead.   In _**Amazon**_ case and it's one of RedHat os family systems; Then the check did not reach Amazon block and therefore it failed.

https://github.com/wazuh/wazuh-puppet/blob/5fef8be6f732f6595d2d992c7dd98c7ef40ea105/manifests/agent.pp#L246-L272

Kr,

Rshad

**Comment by jm404** [comment]
Done in #197
