### ISSUE TITLE
Puppet default path for agent.conf is wrong

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-puppet#169]
**Wazuh version:** 3.10.2

**Elastic version:** 7.3.2

**Environment:**

Any Wazuh Puppet installation

**Is this a bug report or a feature requests?:**

Bug report

**What is the current behavior?**

Current path for `shared_agent_config_file` is wrong as it is declared to :
```
$shared_agent_config_file = '/var/ossec/etc/shared/agent.conf
```
But the shared folder contains groups subfolder so it should be 
```
$shared_agent_config_file = '/var/ossec/etc/shared/default/agent.conf
```

**What is the motivation/use case for changing the behavior?**

Fix default `agent.conf` file path.

**Description**: 
In order to fix this, some task must be performed:

### Tasks

- [x] Update variable path to correct value

- [x] Test the `agent.conf` is properly renderd under the  /default folder

Best regards,

Jose

**Comment by rshad** [comment]
Hi all!

Changes will be made in branch: https://github.com/wazuh/wazuh-puppet/tree/fix-169-agent_conf-path

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

The requested change is applied now. Please check https://github.com/wazuh/wazuh-puppet/commit/049e71fc6ea185c027590cb799b2ecc2efa3c447

kr,

Rshad
