### ISSUE TITLE
HTTPS repository requires apt-transport-https package..

### ISSUE THREAD

**Issue by lemrouch** [wazuh/wazuh-puppet#18]
which is not installed on Debian by default.

FYI: The original
`
          package { 'apt-transport-https':
            ensure => 'installed',
          } ->
          apt::source { 'wazuh':
`
did not cause a dependency cycle.

Does the #17 look better?

**Comment by jlruizmlg** [comment]
Hi @lemrouch yes, looks better, i just merge your pull request! thanks!!
