### ISSUE TITLE
Support for puppet 5

### ISSUE THREAD

**Issue by jchenrev** [wazuh/wazuh-puppet#201]
Sorry for asking a question here but I couldn't find any answer.

I see in metadata.json it requires puppet to `">= 6.0.0 < 7.0.0"`, does it mean I cannot use this module on puppet 5?

Also I'm a bit confused about the version number of this module, e.g. `3.11.1_7.5.1`. Is `7.5.1` the compatible version of ELK stack? Does it mean I need to  use `7.5.1` ELK stack with this puppet module?

**Comment by jchenrev** [comment]
Also, is it true that this puppet module can only install exact same version of wazuh-manager as the module version. For example, wazuh-puppet `3.11.1_7.5.1` can only install wazuh-manager `3.11.1`?

**Comment by jm404** [comment]
Hi @jchenrev,

Most of our changes and tests are performed on Puppet 6 so we considered appropriate to require Puppet 6 or greater for the Wazuh Module. If you consider that Puppet 5 should be supported, we'll be glad to discuss it.

The version after the underscore, `7.5.1` designates the EFK version of the stack compatible and that the Wazuh module installs.

Regarding the wazuh-puppet versions installed, you can change the `server_package_version` to configure the Wazuh Manager version, please ensure that you install compatible versions of Wazuh and EFK (you can also configure the Elastic and Kibana versions).

Versions:

- Wazuh Manager

https://github.com/wazuh/wazuh-puppet/blob/43912a74b6dab3dcb5b67c4ac5328c2ffff822b6/manifests/params_manager.pp#L8

- Filebeat

https://github.com/wazuh/wazuh-puppet/blob/43912a74b6dab3dcb5b67c4ac5328c2ffff822b6/manifests/filebeat.pp#L10-L11

- Elasticsearch

https://github.com/wazuh/wazuh-puppet/blob/devel/manifests/elasticsearch.pp#L14

- Kibana

https://github.com/wazuh/wazuh-puppet/blob/43912a74b6dab3dcb5b67c4ac5328c2ffff822b6/manifests/kibana.pp#L6-L7

**Comment by jchenrev** [comment]
Thanks for the clarification. I'm not sure whether puppet 5 should be supported because it will become obsolete soon. It's just my company still uses puppet 5 at the moment. So I'll need to find a way to tweak it in.

Am I able to use a previous version of wazuh-puppet module that doesn't declare the requirement of puppet 6?

**Comment by jm404** [comment]
Hi @Jchenrev,

I reviewed the related docu to `puppet module install` but there is no option to offer compatibility to previous Puppet versions. Also considered the option `--ignore-dependencies` but the puppet version is not a dependency but a requirement.

You can always clone the `wazuh-puppet` repo and modify the requirements to fit your Puppet version:

https://github.com/wazuh/wazuh-puppet/blob/30ce72896be818c13ea624a38e8905c1dd8e6b9f/metadata.json#L100-L105.

Then using [Puppet Development Kit](https://puppet.com/docs/pdk/1.x/pdk_install.html) you can build your own Wazuh 3.11.1 release tarball file compatible with Puppet 5. You might find useful the related Puppet docu about it: [Install release from tarball](https://puppet.com/docs/puppet/4.10/modules_installing.html#install-from-a-release-tarball).

Hope it helps!

Best regards,

Jose

**Comment by jchenrev** [comment]
I found it the syntax is compatible with puppet 5.5.
Given we are using puppet in a different way I manage to install this module and run it with puppet 5.

**Comment by jchenrev** [comment]
I don't have further questions regarding this, I'll close it for now.
