### ISSUE TITLE
There is no configuration for Reports

### ISSUE THREAD

**Issue by lemrouch** [wazuh/wazuh-puppet#21]
Section for [Reports](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/reports.html) is missing is final _ossec.conf_.
Can you add few variables and template code to server config generation?
Something like #20

**Comment by jlruizmlg** [comment]
Hi @lemrouch thanks for the pull request, let me take a look and verify!

**Comment by lemrouch** [comment]
Or do you want something with all those options from documentation with lots of comments and tests?

**Comment by jlruizmlg** [comment]
Well have all options can be a great idea!, all contributions are always more than welcome! but if you like we can start with this.

I was thinking instead of add more options to the server class, maybe create a new manifest with other class with the reports, like we are doing with Active Response or Addlog, what do you think?

**Comment by lemrouch** [comment]
I'm not sure if you can define reports multiple times. In such case I can do it.
But I find it much easier to redefine few default values in Foreman's Smart Class than creating whole new container class just to call one funtion several times.

**Comment by jlruizmlg** [comment]
Hi @lemrouch we can setup multiples reports with different parameters in the same ossec.conf, something like the following code:

```
 <reports> 
        <category>authentication_success</category> 
        <user type="relation">srcip</user> 
        <title>Daily report: Successful logins</title> 
        <email_to>user1@example.com</email_to> 
 </reports> 

<reports> 
        <category>syscheck</category> 
        <title>Daily report: File changes</title> 
        <email_to>user2@example.com</email_to> 
</reports> 
```

We can send different reports with different to one or more than one email.

**Comment by lemrouch** [comment]
There is new commit ready in pull request.
You can use the class like
```
  wazuh::reports { 'daily':
    r_level    => 4,
    r_title    => 'WAZUH Daily report',
    r_email_to => 'daily@company.com',
  }
```

**Comment by jlruizmlg** [comment]
Hi @lemrouch i already merge your pull request #20 thanks for your contribution as always.

**Comment by JohnKibe** [comment]
Thank you all for the good work..
How can I change the reporting from daily to say Weekly or Monthly?

**Comment by lemrouch** [comment]
I don't think you can. There is nothing about interval in [docs](https://documentation.wazuh.com/3.10/user-manual/reference/ossec-conf/reports.html).

**Comment by JohnKibe** [comment]
Thank you for Pavel..

**Comment by jm404** [comment]
Hi @JohnKibe ,

Let me clarify that although we will implement it in the future, we currently don't support changing the interval in the `<reports>` module.

Best regards,

Jose

**Comment by JohnKibe** [comment]
Hello @Jose

Patiently  waiting for the future implementation. Nice work on Wazuh so
far.

Thank you..

Best Regards

John

**Comment by jose** [comment]
Thanks @JohnKibe, but I think you meant @jm404 😉

**Comment by JohnKibe** [comment]
Sorry for that @jm404 <https://github.com/jm404> .. Best of moments.
