### ISSUE TITLE
Audit package's name is auditd in debian

### ISSUE THREAD

**Issue by djmgit** [wazuh/wazuh-puppet#215]
The audit package is known by the name ```audit``` in RHEL systems however in **Debian** it is known as ```auditd```. Due this, the module fails to install audit on Debain and Debian based systems like Ubuntu.

**Comment by jm404** [comment]
Hi  @djmgit,

Thanks for your contribution, it's really appreciated. We will run automated tests on it and manual review the logs aswell to verify it's working perfectly.

Best regards,

Jose
