### ISSUE TITLE
memory limits to wazuh agents

### ISSUE THREAD

**Issue by ossecowner** [wazuh/wazuh-puppet#217]
hi 
 Can anyone help me about this:
[https://github.com/wazuh/wazuh/issues/3265](url)
my agent is centos 6.9 and it doesn't have systemd to add this line in the [Service] section: LimitAS=100000000
where can I set the memory limit ?
thanks a lot.
@manuasir @jm404 @Zenidd

**Comment by jm404** [comment]
Hi @ossecowner,

I can think of two possible approaches for this:

1. Install `systemd` in your Centos Agent and use it to launch the Wazuh services so you can control the memory as described in the issue you linked.

2. Use `cgroups` to limit the memory the Wazuh Agent cant take. The following references describe examples to limit the memory consumption of a user or a process:

- https://www.thegeekdiary.com/centos-rhel-6-how-to-limit-memory-resources-for-a-specific-user-using-cgroups/

- https://unix.stackexchange.com/questions/44985/limit-memory-usage-for-a-single-linux-process

Please let us know if you face any errors while limiting the memory consumption.

Best regards,

Jose

**Comment by ossecowner** [comment]
thanks for your response @jm404 
According to the link you sent:
- [https://www.thegeekdiary.com/centos-rhel-6-how-to-limit-memory-resources-for-a-specific-user-using-cgroups/](url)
 Do you mean that it is ok if I replace the user "John" with "ossec" in the example of the link?

**Comment by jm404** [comment]
Hi @ossecowner,

Yes, replacing "John" with "ossec" should limit the memory but please note it has to be tested to ensure it works as expected

Best regards,

Jose

**Comment by jm404** [comment]
Hi @ossecowner ,

I'm closing the issue due to inactivity. Feel free to open a new one if you need it.

Best regards,

Jose
