### ISSUE TITLE
Typo in manager.pp

### ISSUE THREAD

**Issue by chnjackso** [wazuh/wazuh-puppet#218]
Typo in manager.pp

Line 147
`$vulnerability_detector_provider_debian_canonical_interval = $wazuh::params_manager::vulnerability_detector_provider_canonical_update_interval,`

Should be
`$vulnerability_detector_provider_canonical_update_interval = $wazuh::params_manager::vulnerability_detector_provider_canonical_update_interval,`

**Comment by rshad** [comment]
Fixed in #237.
