### ISSUE TITLE
this action would add [2] total shards, but this cluster currently has [1000]/[1000] maximum shards open

### ISSUE THREAD

**Issue by ossecowner** [wazuh/wazuh-puppet#222]
hi @jm404 @manuasir @Zenidd 
i can't use my kibana for management and monitoring. it dont accept my 

> Settings. 2011 - Could not save data in elasticsearch due to [validation_exception] Validation Failed: 1: this action would add [2] total shards, but this cluster currently has [1000]/[1000] maximum shards open; (/elastic/api)

I dont have cluster I have 1 wazuh server.
I did these :
- thread_pool.search.queue_size: 10000 in /etc/elasticsearch/elasticsearch.yml but it wasn't solution and I deleted it
- Xms8g  & Xmx8g  in jvm.options  are set. my RAM is 16G

the result of curl http://localhost:9200/_cluster/health?pretty:
{
  "cluster_name" : "elasticsearch",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 987,
  "active_shards" : 987,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 13,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 98.7
}
my elasticsearch version is 7.3
kibana 7.3
 I did all of things in this link"
[https://documentation.wazuh.com/3.9/installation-guide/installing-elastic-stack/elastic_tuning.html](url)
but I still have error message 🤒  
 can anyone help me?  I can't check my agents :((((((

**Comment by manuasir** [comment]
Hello @ossecowner,

I think to increase the total number of shards to 10k could provoke inoperability and performance issues in your Elasticsearch cluster. Can you please describe here your Elasticsearch architecture? Also, this request can provide some info:

```
curl -XGET localhost:9200/_cluster/allocation/explain?pretty
```

After that, please try the following to reallocate the unassigned shards. First, set the replica option to 0:

```
curl -XPUT ' localhost:9200/wazuh-alerts-*/_settings' -H 'Content-Type: application/json' -d '{ "index": { "number_of_replicas": "0" } }'
```

At the same time, execute this in another terminal to see the status:

```
watch -n0 'curl -s localhost:9200/_cluster/health?pretty | grep "active_shards_percent"'
```
If that doesn't work, please try this solution as a workaround. It's about to increase the shards limit to 3k so you can take control of them meanwhile an architectural solution is implemented, because
I think you will probably have to add additional data nodes to your ES cluster in the near future.

```
curl -X PUT localhost:9200/_cluster/settings -H "Content-Type: application/json" -d '{ "persistent": { "cluster.max_shards_per_node": "3000" } }'
```

Let me know if that helps,

Cheers

**Comment by ossecowner** [comment]
The result of what you said:
first:
> {
  "index" : "userindex1",
  "shard" : 0,
  "primary" : false,
  "current_state" : "unassigned",
  "unassigned_info" : {
    "reason" : "CLUSTER_RECOVERED",
    "at" : "2020-03-04T13:54:15.885Z",
    "last_allocation_status" : "no_attempt"
  },
  "can_allocate" : "no",
  "allocate_explanation" : "cannot allocate because allocation is not permitteto any of the nodes",
  "node_allocation_decisions" : [
    {
      "node_id" : "GFdtLs_xSGSYOkCrmkd3Vg",
      "node_name" : "localhost.localdomain",
      "transport_address" : "127.0.0.1:9300",
      "node_attributes" : {
        "ml.machine_memory" : "16657121280",
        "xpack.installed" : "true",
        "ml.max_open_jobs" : "20"
      },
      "node_decision" : "no",
      "deciders" : [
        {
          "decider" : "same_shard",
          "decision" : "NO",
          "explanation" : "the shard cannot be allocated to the same node on wch a copy of the shard already exists [[userindex1][0], node[GFdtLs_xSGSYOkCrm3Vg], [P], s[STARTED], a[id=dH0Q8lgHQRWtdPh4pp43TQ]]"
        }
      ]
    }
  ]
}


 second:
> {"acknowledged":true}

third:
>  "active_shards_percent_as_number" : 98.7

and Finally I increase the shards limit to 3k and it's ok now, thanks a lot.
I install agents continuously and my data is increasing,What suggestions do you have for better performance?
thanks.

**Comment by manuasir** [comment]
Hello @ossecowner ,

I'm glad to hear it is working now. I suggest to horizontally scale your Elasticsearch cluster by adding more data nodes. 
Maybe you might find these resources useful:

- https://www.elastic.co/guide/en/elasticsearch/reference/current/scalability.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/add-elasticsearch-nodes.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#data-node

I think we can already close this ticket. As always, don't hesitate to open a new one if you need it.

Cheers

**Comment by msk134** [comment]
> Hello @ossecowner,
> 
> I think to increase the total number of shards to 10k could provoke inoperability and performance issues in your Elasticsearch cluster. Can you please describe here your Elasticsearch architecture? Also, this request can provide some info:
> 
> ```
> curl -XGET localhost:9200/_cluster/allocation/explain?pretty
> ```
> 
> After that, please try the following to reallocate the unassigned shards. First, set the replica option to 0:
> 
> ```
> curl -XPUT ' localhost:9200/wazuh-alerts-*/_settings' -H 'Content-Type: application/json' -d '{ "index": { "number_of_replicas": "0" } }'
> ```
> 
> At the same time, execute this in another terminal to see the status:
> 
> ```
> watch -n0 'curl -s localhost:9200/_cluster/health?pretty | grep "active_shards_percent"'
> ```
> 
> If that doesn't work, please try this solution as a workaround. It's about to increase the shards limit to 3k so you can take control of them meanwhile an architectural solution is implemented, because
> I think you will probably have to add additional data nodes to your ES cluster in the near future.
> 
> ```
> curl -X PUT localhost:9200/_cluster/settings -H "Content-Type: application/json" -d '{ "persistent": { "cluster.max_shards_per_node": "3000" } }'
> ```
> 
> Let me know if that helps,
> 
> Cheers

This worked for me. Thanks a lot.
Can you please let me know the permanent solution for this. 

Thanks in advance.
sampath.

**Comment by tinhtq** [comment]
curl -u your_username:your_password -X PUT "http://your_elasticsearch_host:9200/_cluster/settings" -H "Content-Type: application/json" -d '{
  "persistent": {
    "cluster.max_shards_per_node": "3000"
  }
}'
change the username and password that are suitable for your elasticsearch
