### ISSUE TITLE
Rootcheck section is missing system audit subsection

### ISSUE THREAD

**Issue by djmgit** [wazuh/wazuh-puppet#227]
```_rootcheck.erb``` is missing ```system_audit``` subsection, as a result of which system audit files cannot be configured using this module.

Reference : https://documentation.wazuh.com/3.11/user-manual/capabilities/policy-monitoring/rootcheck/rootcheck-configuration.html

**Comment by rshad** [comment]
Done in https://github.com/wazuh/wazuh-puppet/pull/228
