### ISSUE TITLE
auditd service & configs don't require auditd package

### ISSUE THREAD

**Issue by chrisboulton** [wazuh/wazuh-puppet#239]
It looks like in `wazuh::audit`, the service & file resources require the auditd package to be installed first. This can lead to situations where the other resources are managed before the package is installed, which causes Puppet to be unable to converge in one run:

```
Error: Systemd start for auditd failed!
journalctl log for auditd:
-- No entries --

Error: /Stage[main]/Wazuh::Audit/Service[auditd]/ensure: change from stopped to running failed: Systemd start for auditd failed!
journalctl log for auditd:
-- No entries --

Notice: /Stage[main]/Wazuh::Audit/Package[Installing Audit...]/ensure: created
```

**Comment by rshad** [comment]
Hi @chrisboulton,

As you can see in the class `wazuh::audit`, we first, install `audit` service.
https://github.com/wazuh/wazuh-puppet/blob/8d766274d7f1478322f6430ff4e664d58c9b4919/manifests/audit.pp#L11-L24

I've never experience a case where the service installation was skipped, taking into account we are dealing with `Linux` kernel.

Could you please provide the complete `Puppet` log and more info about.
- `wazuh-puppet` branch and its last commit.
- `OS`
- `OS release`.

Kr,

Rshad

**Comment by chrisboulton** [comment]
The above won't enforce any kind of ordering - if you want to ensure the package is installed before starting the service, then you need either resource chaining or an explicit require on the service. Puppet makes no certain guarantee guarantee of "top to bottom" execution of a manifest when it's in the apply phase:

> By default, Puppet applies resources in the order they’re declared in their manifest. **However, if a group of resources must always be managed in a specific order, you should explicitly declare such relationships with relationship metaparameters, chaining arrows, and the require function.**

It's hard to provide you with a reproducible example here, because it's probably environment (as in, our other Puppet manifests) dependant.

**Comment by rshad** [comment]
Hi @chrisboulton,

I agree with you, that no order is guaranteed but as I've never experienced an error, I did not establish a strict order. I will add this strict order, test it, and I'll be back with results.

Thank you,

Kind regards.

Rshad

**Comment by rshad** [comment]
Working branch: [feature-239-order-audit-module](https://github.com/wazuh/wazuh-puppet/tree/feature-239-order-audit-module).

**Comment by rshad** [comment]
Hi @chrisboulton,

After adding the required changes as you can check in https://github.com/wazuh/wazuh-puppet/pull/242/files, we guarantee a strict order between the tasks of the class `wazuh::audit` so we can be sure that the installation task of the service `audit` will run first.

Kr,

Rshad

**Comment by chrisboulton** [comment]
Looks great - thanks a bunch!
