### ISSUE TITLE
Manager config param `local_ip` is not exposed

### ISSUE THREAD

**Issue by alanwevans** [wazuh/wazuh-puppet#250]
The `local_ip` parameter in the `remote` section of the manager config is not exposed in this puppet module.

https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/remote.html

For that matter neither are `allowed-ips`, `denied-ips` and `ipv6`.  But I do not have a good way to test these so I have left them out of my patch.

**Comment by manuasir** [comment]
Thank you @alanwevans for reporting this missing parameter, we will review your pull request and once the tests are passed it'll be merged and shipped along with the upcoming release.

Regards
