### ISSUE TITLE
deleting osquery logs

### ISSUE THREAD

**Issue by ossecowner** [wazuh/wazuh-puppet#254]
hello my dear frieds
I enabled osquery in wazuh. now I have a question. Will the log files be deleted after a while? Or should I write in the config file? 
I don't want osquery logs to fill the agents disk space.
thanks

**Comment by jm404** [comment]
Hi @ossecowner,

Osquery does not provide log rotation, this means that your `/var/log/osquery` folder will be growing every day. If you need to rotate them you have to do it manually, either using a custom script or a log rotation service.

You can create a script that runs daily and checks the creation date of osquery's logs files and if its greater than your desired value remove them. Also, there are some software solutions like `logrotate` that can help you to achieve this.

Let me know if you need further help.

Best regards,

Jose

**Comment by ossecowner** [comment]
thanks for your response.
Thank you very much for always answering the questions patiently.

**Comment by jm404** [comment]
You are welcome! Let me close this issue and please feel free to open a new one anytime.

Best regards,

Jose
