### ISSUE TITLE
Unscheduling refresh on Service[wazuh-agent]

### ISSUE THREAD

**Issue by lemrouch** [wazuh/wazuh-puppet#26]
_/etc/init.d/wazuh-agent status_ is checking all processes and it's common the _ossec-execd_ is not running. The init script returns non zero status and puppet thinks wazuh_agent service not running at all.
This leads into
```
Notice: /Stage[main]/Wazuh::Client/Service[wazuh-agent]/ensure: current_value stopped, should be running (noop)
Info: /Stage[main]/Wazuh::Client/Service[wazuh-agent]: Unscheduling refresh on Service[wazuh-agent]
```
Then puppet tries to start the agent instead of reload. And since the agent is already running the start command does nothing in the end - not even reload after configuration change.
Therefore the puppet refresh of wazuh_agent service is broken.
I guess change in the init script or migration to systemd service might solve this.
What do you think?

**Comment by jlruizmlg** [comment]
Hi @lemrouch you are right, we are working in a better service, let me think how we can fix this issue, meanwhile let me think in the best solution to fix this issue.

**Comment by ajurjevi** [comment]
Any solution on this? And Wazuh 3.x adds wazuh-clusterd in the mix...

**Comment by Fabian1976** [comment]
I fixed this on rhel/centos 7 by adding this to the node yaml:
wazuh::server::ossec_service_provider: 'systemd'

**Comment by JPLachance** [comment]
Hello!

I just deployed the latest version of this module in my development environment and I'm observing the same behavior. I currently install Wazuh on Ubuntu instance only.

Do we have a fix? It's not a deal breaker, but it's a little annoying to see each Puppet run doing something useless 🙂 

Thanks!

**Comment by jm404** [comment]
Hi @lemrouch, @Fabian1976, @ajurjevi, @JPLachance 

Sorry for the late response, we will investigate it in order to find out what is causing the error.

Some environment details would be very appreciated:

- Target OS (Architecture and version)
- Puppet Version
- Wazuh Puppet Branch

Thanks for your patience,

Best Regards

Jose

**Comment by rshad** [comment]
Hi all!

Today we tested `wazuh-agent` functionality using `wazuh``3.9.5` on Debian platofrm:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

We believe that the issue mentioned here is not existing anymore in the recent versions of Wazuh, because all the checks we ran today were passed successfully.

* **Output: ossec-control status**
```
root@debian-2:/var/ossec/bin# ./ossec-control status
wazuh-modulesd is running...
ossec-logcollector is running...
ossec-syscheckd is running...
ossec-agentd is running...
ossec-execd is running...
```

**Note** `ossec-execd` is started automatically.

* **Output: systemctl status  wazuh-agent**
```
root@debian-2:/var/ossec/bin# systemctl status wazuh-agent
● wazuh-agent.service - Wazuh agent
   Loaded: loaded (/etc/systemd/system/wazuh-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-08-21 13:46:57 UTC; 4min 0s ago
  Process: 15246 ExecStart=/usr/bin/env ${DIRECTORY}/bin/ossec-control start (code=exited, status=0/SUCCESS)
    Tasks: 24
   Memory: 377.6M
      CPU: 37.275s
   CGroup: /system.slice/wazuh-agent.service
           ├─15695 /var/ossec/bin/ossec-execd
           ├─15700 /var/ossec/bin/ossec-agentd
           ├─15707 /var/ossec/bin/ossec-syscheckd
           ├─15712 /var/ossec/bin/ossec-logcollector
           └─15722 /var/ossec/bin/wazuh-modulesd

Aug 21 13:46:55 debian-2 systemd[1]: Starting Wazuh agent...
Aug 21 13:46:55 debian-2 env[15246]: Starting Wazuh v3.9.5...
Aug 21 13:46:55 debian-2 env[15246]: Started ossec-execd...
Aug 21 13:46:55 debian-2 env[15246]: Started ossec-agentd...
Aug 21 13:46:55 debian-2 env[15246]: Started ossec-syscheckd...
Aug 21 13:46:55 debian-2 env[15246]: Started ossec-logcollector...
Aug 21 13:46:55 debian-2 env[15246]: Started wazuh-modulesd...
Aug 21 13:46:57 debian-2 env[15246]: Completed.
```

![wazuh-puppet_works](https://user-images.githubusercontent.com/19154337/63438501-abb6cd80-c42c-11e9-9270-7b03c0fd835f.PNG)

Kind regards,

Rshad

**Comment by manuasir** [comment]
This issue will be closed since this doesn't apply to the current version of Wazuh. @lemrouch if you still facing this issue, please don't hesitate to open a new issue.

Thanks
