### ISSUE TITLE
Unable to register agent with multiple HA cluster nodes 

### ISSUE THREAD

**Issue by hairiest** [wazuh/wazuh-puppet#260]
I am using the module to deploy agents to ubuntu server, I have a HA cluster (2 node) but params only accept reporting server and registration server - how do i register multiple reporting servers?

**Comment by jm404** [comment]
Hi @hairiest ,

You can check the related documentation at https://documentation.wazuh.com/3.12/user-manual/configuring-cluster/basics.html

To configure these parameters, you can use the Manager parameters.

https://github.com/wazuh/wazuh-puppet/blob/c801e3aa8cffce4b6ee2000a586965d383cfc08f/manifests/params_manager.pp#L264-L276

When defining a manifest, you can override them to configure the `<cluster>` config block of your master and workers (note the config varies betweeen master and workers).

Let me know if you have any issue or doubt about it

Best regards,

Jose

**Comment by hairiest** [comment]
Hi Jose - apologies this relates to the agent_params. whereby i can have an agent config point to two reporting_endpoints.  currentlyu there is only a single reporting endpoint in the agent template file

wazuh_reporting_endpoint  - which suggests a single master

we currently have a 2 node cluster (master/worker) so we want to point agent to both nodes i.e. wazuh_reporting_endpoint2 ?

**Comment by jm404** [comment]
Hi @hairiest,

Sorry for the late response, the `wazuh_reporting_endpoint` is rendered inside the `<adress>` tags: 
![image](https://user-images.githubusercontent.com/46649922/83860039-08b31400-a71f-11ea-9690-2427e90af803.png)

If you want to add multiple hosts, you can do it by declaring `wazuh_reporting_endpoint`  to `server1,server2,server3` for example. This way you can use multiple adresses within the same variable

Hope it helps!

Best regards,

Jose
