### ISSUE TITLE
Duplication of a class name

### ISSUE THREAD

**Issue by wikitops** [wazuh/wazuh-puppet#261]
In some cases, depending on the way someone manage the deployment of the agents and the managers, a definition can be duplicated because it has the same name.

In the file agent.pp and manager.pp, this code has the same name :

```
  # Extract from agent.conf line 320
  concat { 'ossec.conf':
    path    => $wazuh::params_agent::config_file,
    owner   => $wazuh::params_agent::config_owner,
    group   => $wazuh::params_agent::config_group,
    mode    => $wazuh::params_agent::config_mode,
    before  => Service[$agent_service_name],
    require => Package[$agent_package_name],
    notify  => Service[$agent_service_name],
  }

  # Extract from manager.conf line 380
  concat { 'ossec.conf':
    path    => $wazuh::params_manager::config_file,
    owner   => $wazuh::params_manager::config_owner,
    group   => $wazuh::params_manager::config_group,
    mode    => $wazuh::params_manager::config_mode,
    require => Package[$wazuh::params_manager::server_package],
    notify  => Service[$wazuh::params_manager::server_service],
  }
```

This can result in an error during the execution of Puppet.

In both definition, the name is not really important because all the options are set in the class concat so I suggest to update the name of each class to make it unique and avoid any duplication error ... again in some cases.

**Comment by jm404** [comment]
Hi @wikitops,

I share your point of view, the `concat` blocks should have a better naming convention like `manager_ossec.conf` and `agent_ossec.conf` for example.

We will address it and let you know the updates.

Thanks for sharing! It's really appreciated

Best regards,

Jose

**Comment by Zenidd** [comment]
Hello again @wikitops, 

We just [merged a fix](https://github.com/wazuh/wazuh-puppet/pull/293) changing the naming convention for the manager and agent concat resources. There should be no collisions at all now. 

Thanks for your contribution and let us know anything we should improve. 

Greetings,

JP
