### ISSUE TITLE
Syslog output configuration not applied

### ISSUE THREAD

**Issue by lennartkoopmann** [wazuh/wazuh-puppet#273]
I'm setting the `syslog_output_*` configuration as follows:

```
  class { 'wazuh::manager':
    configure_active_response => false,
    ossec_remote_port         => 1514,
    ossec_remote_protocol     => 'udp',
    ossec_remote_connection   => 'secure',
    manage_repos              => true,
    agent_auth_password       => '[REDACTED]',
    syslog_output             => true,
    syslog_output_server      => '172.30.0.6',
    syslog_output_port        => 5514,
    syslog_output_format      => 'cef'
  }
```

This does however not lead to any configuration written to `ossec.conf`. If I stop puppet and add my configuration to the file manually, all alerts are sent via syslog as expected. This is the config I'd expect the module to write:

```
<syslog_output>
  <server>172.30.0.6</server>
  <port>5514</port>
  <format>cef</format>
</syslog_output>
```

See also:

* https://documentation.wazuh.com/3.13/user-manual/reference/ossec-conf/syslog-output.html
* https://documentation.wazuh.com/3.13/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-manager-class.html#reference-wazuh-manager-class

**Comment by Zenidd** [comment]
Hello @lennartkoopmann,

You are right, I just verified that the `syslog_output` option isn't working at all. While there are placeholders for this section options, there is no related ERB template to include it on the final rendered `ossec.conf` file.

We will address it and let you know the updates.

Thanks for sharing! It's really appreciated

Best regards,
JP

**Comment by lennartkoopmann** [comment]
Thank you! I'll be happy to test or assist in any way.

**Comment by manuasir** [comment]
Done here #276

**Comment by lennartkoopmann** [comment]
Hi! Thanks for the fix. Absolutely awesome turnaround time. :+1:

Do you know already when a release with the fix included will come out? I can't wait to deploy it.
