### ISSUE TITLE
misleading message

### ISSUE THREAD

**Issue by rleite-olx** [wazuh/wazuh-puppet#28]
Greetings,

I just found a misleading message at /etc/puppetlabs/code/environments/staging/modules/wazuh/manifests/server.pp:51

``` 
if $smtp_server == undef {
      fail('$ossec_emailnotification is enabled but $ossec_emailnotification was not set')```

i think you're talking about the $smtp_server instead. :-)

All my best!

**Comment by jnarvaezp** [comment]
Hi @rleite-olx 

I apologize first for the delay in replying.
This message has already been fixed for the next puppet version.

Thank you for your collaboration.
