### ISSUE TITLE
Modify Template to allow Elasticsearch cluster

### ISSUE THREAD

**Issue by akshatgit** [wazuh/wazuh-puppet#292]
https://github.com/wazuh/wazuh-puppet/blob/7c1d4b4ab1941392a54ef4faf4cf1197dd744481/templates/kibana_yml.erb#L31

Apologies for flooding the repo with issues. 😅 

Thanks 
Akshat

**Comment by Zenidd** [comment]
Hello @akshatgit,

As you have already noticed, our `kibana.yml` template supports just pointing a single ES node. 

We are in the process of enhancing the manifests and templates and add new features like SSL certificates generation and distribution, Opendistro support, and others. You can track our progress here https://github.com/wazuh/wazuh-puppet/issues/287. I'm referencing this issue in #287 so it will be taken into account and if possible, included in the same PR.

Thanks for your contribution, do not hesitate to let us know anything that we should improve.

Greetings,

JP
