### ISSUE TITLE
Active response defined-agent does not provide a way to specify agent-id

### ISSUE THREAD

**Issue by ddholstad99** [wazuh/wazuh-puppet#3]
The active response section can be set to defined-agent, but the template does not have an agent-id section, so there is no way to use it.

**Comment by jlruizmlg** [comment]
hi @ddholstad99 you are right, we will add this option as soon as possible, thanks for let us now!

**Comment by ddholstad99** [comment]
Thank you for getting this done so quickly!

**Comment by jlruizmlg** [comment]
@ddholstad99 sure! please feel free to close the issue if works for you!

All recommendations are more than welcome!!

**Comment by ddholstad99** [comment]
This looks good to me
