### ISSUE TITLE
Availability on Puppet Forge

### ISSUE THREAD

**Issue by lennartkoopmann** [wazuh/wazuh-puppet#316]
Hi team,

the recent releases have not shown up on the [wazuh/wazuh Puppet Forge page](https://forge.puppet.com/modules/wazuh/wazuh) yet. Is this planned to happen in the future?

Thank you!

**Comment by neonmei** [comment]
Hi @lennartkoopmann,
Yes, this is definitely on the roadmap for the coming releases. As soon as our workflow allows us we will address it. Thanks for reporting!

Regards.

**Comment by Zenidd** [comment]
Hey @lennartkoopmann,

I'm happy to announce that we just released `wazuh-puppet` v4.0.4 on Puppet forge. We plan to keep releasing it after any main product release. Thanks for your interest in the project.

_-JP_

**Comment by lennartkoopmann** [comment]
That's awesome! Thank you!
