### ISSUE TITLE
Active-response, command and localfile options related manifests not working properly

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-puppet#322]
Hi team,

### Wazuh::Command (command.pp)

- The concat resource in `command.pp` has `ossec.conf` as target:
https://github.com/wazuh/wazuh-puppet/blob/cb69e44afdaea649909a0f7f61d31ffd68b4b9b0/manifests/command.pp#L13 However, the concat resource in manager side is named `manager_ossec.conf`. It leads to the hereunder error.
```
Warning: /Stage[main]/Profile::wazuh::Manager/Wazuh::Command[firewallblock]/Concat::Fragment[firewallblock]/Concat_fragment[firewallblock]: Target Concat_file with path or title 'ossec.conf' or tag 'ossec.conf not found in the catalog
```

- target, order, and content `concat` options should take their value from a variable instead of being hardcoded.
- documentation examples lack some variables

----
### Wazuh::Activeresponse (activeresponse.pp)

- The concat resource in `activeresponse.pp` has `ossec.conf` as target:
https://github.com/wazuh/wazuh-puppet/blob/cb69e44afdaea649909a0f7f61d31ffd68b4b9b0/manifests/activeresponse.pp#L16 However, the concat resource in manager side is named `manager_ossec.conf`. It leads to the hereunder error.

```
Warning: /Stage[main]/Profile::wazuh::Manager/Wazuh::Activeresponse[blockattack]/Concat::Fragment[Rendering active-response template]/Concat_fragment[Rendering active-response template]: Target Concat_file with path or title 'ossec.conf' or tag 'ossec.conf not found in the catalog
```

- [Example manifests](https://documentation.wazuh.com/4.0/deploying-with-puppet/wazuh-puppet-module/#install-manager-via-puppet) in Wazuh documentation still show the use of old and removed variables (ar_*).  These should be updated with the new ones (active_response_*).
```ruby
  wazuh::activeresponse { 'blockWebattack':
      command_name => 'firewall-drop',
      ar_level     => 9,
      ar_agent_id  => 123,
      ar_rules_id  => [31153,31151],
      ar_repeated_offenders => '30,60,120'
  }
```
- Besides the `ar_*` to `active_response_*` update, the following variable also has an incorrect value  `ar_repeated_offenders => '30,60,120'` should be `ar_repeated_offenders => [30,60,120]`

- Wazuh::Activeresponse fragment `order` has `undef` value. It leads to error as the active-response block is placed over the related command definition.
```
Dec 10 09:59:08 master env[24464]: 2020/12/10 09:59:08 ossec-analysisd: ERROR: (1303): Invalid command 'firewall-drop' in the active response.
Dec 10 09:59:08 master env[24464]: 2020/12/10 09:59:08 ossec-analysisd: ERROR: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.
Dec 10 09:59:08 master env[24464]: 2020/12/10 09:59:08 ossec-analysisd: CRITICAL: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.
```
-----
### Wazuh::Addlog ( addlog.pp )

- As the two previous ones, the concat resource in `addlog.pp` has `ossec.conf` instead of `manager_ossec.conf` as target. Related error
```
Warning: /Stage[main]/Profile::wazuh::Manager/Wazuh::Addlog[monitorLogFile]/Concat::Fragment[ossec.conf_localfile-/var/log/auth.log]/Concat_fragment[ossec.conf_localfile-/var/log/auth.log]: Target Concat_file with path or title 'ossec.conf' or tag 'ossec.conf not found in the catalog
```
- target, order, and content `concat` options should take their value from a variable instead of being hardcoded.
- documentation examples lack some variables

**Most of these bugs were reported by @ialokin through the Wazuh Slack community Channel. Credits to him.**

Greetings,

JP

**Comment by ialokin** [comment]
`ar_repeated_offenders => '30,60,120' should be ar_repeated_offenders => [30,60,120]`

I actually had to change `ar_` to `active_response_` on the variables in order for it to run.

**Comment by Zenidd** [comment]
Hello @ialokin, 

Just updated the issue to clarify the `ar_*` -> `active_response_*` variables port.

Greetings,

JP
