### ISSUE TITLE
Wazuh v4.1.5 support

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-puppet#363]
We need to bump the repository to v4.1.5 version

**Comment by jcruzlp** [comment]
## Progress Update

- Studying how puppet works

**Comment by shaunbugler** [comment]
Yes this needs to happen so that we can use NVD vulnerability detection feed as it was only fixed in 3.13 and 4.1 and not 4.0

**Comment by alberpilot** [comment]
Hello @shaunbugler 

  The `3.13` branch is, indeed, outdated. We will bump it to `3.13.3` soon. The branch `4.0` is updated because it refers to the latest `4.0.x` version which is `4.0.4`. The branch `4.1` is updated because it contains the latest wazuh version. 

  Actually, if you want to use a Wazuh deployment with puppet free of the NVD Vulnerability bug, you should use the `4.1` branch, which is `4.1.5` and it's working. If you have `3.13.2`, you will need to wait for the `3.13.3` bump. The `4.0` branch doesn't contain the NVD bug fix, because we decided to release only two new versions: `3.13.3` and `4.1.5` for fixing this issue. We decided not to release `4.0.5`, we encourage `4.0.x` users to upgrade to `4.1.5` which contains notable improvements. 

Regards,
Alberto R

**Comment by alberpilot** [comment]
Tag [v4.1.5](https://github.com/wazuh/wazuh-puppet/tree/v4.1.5) done.

**Comment by devicenull** [comment]
What happened to this version?  Puppet forge shows it was deleted

**Comment by shaunbugler** [comment]
I wonder if it has to go with #370 as it mentions redoing the 4.1.5 tag?

**Comment by okynos** [comment]
Hello, @devicenull and @shaunbugler thanks for the reminder.
I have uploaded a `-2` release with the fix of Elasticsearch basic license version that was the reason for `-1` removal.

Take a look at this link https://forge.puppet.com/modules/wazuh/wazuh/4.1.5-2

Please feel free to open us an issue if you detect any errors. I will close this issues for now :)

Regards.
