### ISSUE TITLE
New branching model repository update

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-puppet#365]
We need to keep updated the repository with:
- README updates, indicating the new branching model, where master contains the latest changes and what other branching are actives (4.0, 4.1, 4.2, stable). 
- Bump master branch with 4.3.0 version
- Create a new 4.2 branch and bump it to 4.2.0. 
- Bump 5.0-dev to 5.0.0 version. 
- Bump 3.13 with v3.13.3

**Comment by jcruzlp** [comment]
## Progress update

- Created the 4.2 branch from master since it can't be made from 4.1.
