### ISSUE TITLE
Release 4.2.1 puppet

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-puppet#388]
- [x] #389
- [x] Test 4.2 puppet branch deployment 
- [x] Create v4.2.1 wazuh-puppet tag 
- [x] Create v4.2.1 release into wazuh-puppet GitHub release page 
- [ ] Upload Wazuh Puppet module to forge

**Comment by okynos** [comment]
Tag: https://github.com/wazuh/wazuh-puppet/releases/tag/v4.2.1
Release: https://github.com/wazuh/wazuh-puppet/releases/tag/v4.2.1
