### ISSUE TITLE
apt::key definition causes issues w/ proxy

### ISSUE THREAD

**Issue by redst011** [wazuh/wazuh-puppet#395]
I'm using v4.2.1 of the wazuh module for Puppet and have run into an issue when attempting to obtain the Apt key.

In lines 12-17 of manifests/repo.pp, the key is being defined using both ```source``` and ```server```.  This definition causes the puppetlabs-apt module to generate the ```apt-key``` command in such a way that ignores ```apt::key_options```.

I opened [a call w/ Puppet for puppetlabs-apt](https://tickets.puppetlabs.com/browse/MODULES-11176).  They reviewed, declined to fix, and suggested code that removes the ```source``` from the ```apt::key``` definition.

Would it be possible to define the key as follows to overcome this issue?

```
      apt::key { 'wazuh':
        id     => '0DCFCA5547B19D2A6099506096B3EE5F29111145',
        server => 'pgp.mit.edu'
      }
```

Thank you.

**Comment by vcerenu** [comment]
Hello @redst011 

In order to delete the "source" line inside apt: key it is necessary to also modify apt: source, in this way you can add the customization you want to do in the repo.pp manifest.

```
      apt::key { 'wazuh':
        id     => '0DCFCA5547B19D2A6099506096B3EE5F29111145',
        server => 'pgp.mit.edu'
      }
      case $::lsbdistcodename {
        /(jessie|wheezy|stretch|buster|sid|precise|trusty|vivid|wily|xenial|yakketi|bionic|focal)/: {

          apt::source { 'wazuh':
            ensure   => present,
            comment  => 'This is the WAZUH Ubuntu repository',
            location => 'https://packages.wazuh.com/4.x/apt',
            release  => 'stable',
            repos    => 'main',
            key      => {
              'id'     => '0DCFCA5547B19D2A6099506096B3EE5F29111145',
              'server' => 'pgp.mit.edu',
            },
            include  => {
              'src' => false,
              'deb' => true,
            },
          }
        }
```
We must analyze this change to know if we are going to be able to add it in any next release and we will inform you when we conclude the analysis.

Regards.

**Comment by redst011** [comment]
Hi @vcerenu,

Sorry for the delay.  I've grabbed the code and made the change, but am unable to push back to the repo...  Do I have write access to the repo?

Thanks.
