### ISSUE TITLE
Puppet set ossec.conf to 0440 when RPM sets it to 0640

### ISSUE THREAD

**Issue by juliovalcarcel** [wazuh/wazuh-puppet#41]
When applying the Standard System Security Profile on Centos 7 it requires you to set the permissions of files to equal what they are set as via the RPM install (https://static.open-scap.org/ssg-guides/ssg-centos7-guide-standard.html#xccdf_org.ssgproject.content_rule_rpm_verify_permissions) this fails with wazuh's ossec.conf when applying it with puppet because puppet always sets it to 0440 when the rpm sets it to 0640 thus creating a recursive issue with one resetting the other.

**Comment by juliovalcarcel** [comment]
I can create a pull request for the module if you are okay with changing this behavior in puppet to match the RPM.

**Comment by jlruizmlg** [comment]
Hi @juliovalcarcel sure! we will appreciate that!
