### ISSUE TITLE
Manage repos for Elastic/Kibana/Filebeat

### ISSUE THREAD

**Issue by guillaumeesposito** [wazuh/wazuh-puppet#416]
Hello,

I noticed that we can manage our own repository to install wazuh-manager package here : https://github.com/wazuh/wazuh-puppet/blob/master/manifests/manager.pp#L367

Would it be possible to do the same for Elastic/Kibana/Filebeat package installation ?

Plus, I see that after installation of Filebeat for example, there is a exec of curl command (https://github.com/wazuh/wazuh-puppet/blob/master/manifests/filebeat_oss.pp#L41), wouldn't it be simpler to use a `file` puppet resource ?

Thank you for your help.
Regards,
Guillaume

**Comment by vcerenu** [comment]
HI @guillaumeesposito 

About the repositories, each one of the applications is parameterized in the repo_ files with the name of each application in https://github.com/wazuh/wazuh-puppet/blob/master/manifests.
The Kibana installation is done with a package modified by Wazuh, which is parameterized at https://github.com/wazuh/wazuh-puppet/blob/master/manifests/kibana.pp#L27.

About the second question, we can take the topic to see it in a later release. If you want, you can send a PR or create a branch with the change that you comment; we can verify it and make it part of the releases sooner. Thanks for the input.

Regards
