### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by sazzle2611** [wazuh/wazuh-puppet#42]
Is there any chance of adding support for Darwin?

**Comment by jnarvaezp** [comment]
Hi @sazzle2611 

Currently we have no support but it would be an interesting feature for the future. We can take this into account for an upcoming version
Thanks

**Comment by sazzle2611** [comment]
Thank you @jnarvaezp 

I have created a basic puppet module at https://bitbucket.org/sazzle/sazzle-wazuh_macos that works on MacOS Sierra (not tested on any others yet). It includes a bit of a hack as the agent wouldn't start due to missing files /Library/Ossec/lib/libcrypto.1.0.0.dylib and /Library/Ossec/lib/libssl.1.0.0.dylib. This was the case even if I installed the package manually so I found both the files and included them in the module but I guess this is probably not a good practice. This module also requires your module as it only sets up agents on macs. It uses your module to export agent key to server.

It would be great if this feature could be added to your package sometime so feel free to use any of my module if it helps at all. If there's anything I can do to help then please ask. I do understand that this isn't on the cards yet but will keep my fingers crossed for the future as our company insists on using all 3 platforms Linux/Windows/Macs.

Thanks again, Sarah

**Comment by jnarvaezp** [comment]
Hi @sazzle2611 

Thanks for the code, we'll look at how to integrate the installation of the agent for MacOS with puppet.

Regards.

JN

**Comment by manuasir** [comment]
Hi folks,

This issue is going to be closed due to inactivity. A new issue about this will be opened if this feature is decided to be added to our roadmap for upcoming releases.

Thanks
