### ISSUE TITLE
Wazuh agent (tagged version 4.2.3) forces Windows clients to run a corrective action on every Puppet run

### ISSUE THREAD

**Issue by oletos7j** [wazuh/wazuh-puppet#421]
This is happening on all supported Windows OS versions (10, 2012 R2, 2016, and 2019). 

ensure changed '4.2.3' to '4.2.3-1' (corrective)

Package[Wazuh Agent]
File:  /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/agent.pp Line:  295

**Comment by vcerenu** [comment]
Hello @oletos7j 

This error was reported and we have already made a correction:
https://github.com/wazuh/wazuh-puppet/pull/420

It will be available for the next Wazuh stable release.

Regards.
