### ISSUE TITLE
Support for OracleLinux

### ISSUE THREAD

**Issue by ccjoelm** [wazuh/wazuh-puppet#43]
In params.pp there is a case statement inside the case for RedHat OS Family.  Need to get OracleLinux added in that check for operatingsystem

**Comment by jlruizmlg** [comment]
Thanks @ccjoelm we will take a look, we don't have specific packages for OracleLinux right now, we know that RHEL packages are fully compatible, but we need to review if the same repositories that RHEL works, or we need to create specific repository for this Distribution.

**Comment by ccjoelm** [comment]
Hi

We are using the rhel7 repo for our OracleLinux boxes without and issue, so
I think it is just a matter of allowing it in the puppet module.

Thanks...Joel

**Comment by jlruizmlg** [comment]
Thanks for the information, we will include as soon as possible!.

**Comment by jlruizmlg** [comment]
hi @ccjoelm 

```
We need some ohai information like:

—> ::osfamily
—> ::lsbdistcodename
—> ::operatingsystem
—> ::operatingsystemrelease 
```

In order to do the modifications in or code, thanks.

**Comment by ccjoelm** [comment]
Sure, it will mainly be the same as RedHat with the exception of the
operatingsystem itself:

osfamily: RedHat
lsdistcodename: - not present on RedHat osfamily
operatingsystem: OracleLinux
operatingsystemrelease: 6.*,7.*
operatingsystemmajrelease: 6,7

**Comment by jlruizmlg** [comment]
@ccjoelm i forgot to ask the $releaserver? in Redhat is 6Sercer, 7Server ... in CentOS is 6,7 in Oracle?

**Comment by ccjoelm** [comment]
I don't see that anywhere in the facter results

**Comment by ccjoelm** [comment]
After talking with Sean R. I realized you were talking about the variable for yum, not a facter fact...  OEL uses 6Server, 7Server, etc..

Thanks..Joel
