### ISSUE TITLE
Adapt the Puppet deployment to use the new Wazuh indexer default ports.

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-puppet#447]
As mentioned in https://github.com/wazuh/wazuh-packages/issues/1285, the Wazuh indexer must use the same default ports as elasticsearch. We need to change all deployment-involved files to 9200 and 9300 as default ports.

**Comment by vcerenu** [comment]
Made changes to the PR https://github.com/wazuh/wazuh-puppet/pull/449
