### ISSUE TITLE
Clean wazuh-puppet repository

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-puppet#457]
It is necessary to remove all deployments that do not correspond to the new Wazuh stack:

manifests/kibana_od.pp
manifests/kibana.pp
manifests/opendistro.pp
manifests/elasticsearch.pp

Check if these files are necessary:
manifests/repo_elastic.pp
manifests/repo_elastic_oss.pp

**Comment by alberpilot** [comment]
Done https://github.com/wazuh/wazuh-puppet/pull/462
