### ISSUE TITLE
Some settings aren't working for Wazuh manager/agent class (localfile, remote, email and enrollment sections)

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-puppet#459]
### Description 

During the testing for the 4.3.0 RC5 version over the puppet module https://github.com/wazuh/wazuh/issues/12877, some settings didn't work as expected:

- [x] To configure the **localfiles** section, the variable `ossec_local_files` shouldn't be used. Instead, we need to modify `params_manager.pp/params_agent.pp`. But these changes are only detected by the puppet agents under Ubuntu OS. The CentOS 7/8 puppet agents didn't see the change in these files

![default_localfile_works_for_agent_ubuntu_and_not_for_centos](https://user-images.githubusercontent.com/65046601/161082345-0ceb7921-16df-483e-9aad-bd3961737be0.png)

- [x] The `ossec_remote_connection` variable sets the corresponding [connection](https://documentation.wazuh.com/4.2/user-manual/reference/ossec-conf/remote.html#connection) setting. But if we define it like **syslog**, the puppet module sets a default value for [queue_size](https://documentation.wazuh.com/4.2/user-manual/reference/ossec-conf/remote.html#queue-size) and Wazuh can't start

![master_queue_size_fails_when_ossec_remote_connection_is_set](https://user-images.githubusercontent.com/65046601/161083560-fe65ca22-9284-454b-a0b6-e456ef60cbe1.png)

- [x] The following settings aren't written in the **ossec.conf** file

1. ossec_smtp_server
2. ossec_emailto
3. ossec_emailfrom
4. ossec_email_maxperhour
5. ossec_email_log_source
6. ossec_email_idsname

- [x] The variable `ossec_config_profiles` doesn't work, it should be analyzed
- [x] None of the `Agent enrollment variables` is written in the **ossec.conf** file
- [x] The `configure_active_response` variable for the agent should be tested

**Comment by teddytpc1** [comment]
Regarding the `ossec_local_files` parameter, I've tested it like this in the agent's manifest:
```
    ossec_local_files => [
            { 'location' => '/var/log2/syslog', 'log_format' => 'syslog' },
            { 'location' => '/var/log2/kern.log', 'log_format' => 'syslog' },
            { 'location' => '/var/log3/auth.log', 'log_format' => 'syslog' },
            { 'location' => '/var/lo4g/dpkg.log', 'log_format' => 'syslog' },
            { 'location' => '/var/ossec/logs/active-responses.log', 'log_format' => 'syslog' },
          ],
```
And it works just fine.
I have also tested with v4.2.6 and v4.3.0 with the default values in `params_manager.pp/params_agent.pp` and it is working for Ubuntu Focal and CentOS 7. Have you checked if the `localfile` configuration is in the CentOS 7 `ossec.conf`? Finally, the `default_local_files` in `params_manager.pp/params_agent.pp` contains a `case` statement in order to have different configurations for each OS family (Debian, RHEL, etc.). If you are going to modify the CentOS `default_local_files` parameter, make sure you are changing the value within the `RedHat` case.

**Comment by teddytpc1** [comment]
The `ossec_email` and `ossec_smtp` variables are only added if `ossec_emailnotification` is set to `true`, e.g.:
```
    ossec_emailnotification => true,
```

**Comment by teddytpc1** [comment]
The parameter `ossec_config_profiles` does not exist in the repo. It might be deprecated.

**Comment by teddytpc1** [comment]
For the `Agent enrollment variables` you need to set the `wazuh_enrollment_enabled` to `yes`.

**Comment by pereyra-m** [comment]
Hi @teddytpc1 !

Thank you very much for your comments.
Some of the items I described are in fact configuration mistakes and not real errors of the module.

I'll update the documentation issue https://github.com/wazuh/wazuh-documentation/issues/4997

Regards.

**Comment by teddytpc1** [comment]
The logic for `queue_size` was added in this [PR](https://github.com/wazuh/wazuh-puppet/pull/478).

**Comment by teddytpc1** [comment]
@pereyra-m I think we should close this issue.
