### ISSUE TITLE
Syscheck variables with no effect, errors and dependencies not found for installation.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-puppet#464]
# Description 

## Class 
Manager
## Behavior
- [x] As a consequence of the `whodata` option for `Syscheck` we need the `auditd` package installed on Linux systems. The provisioning fails to install that required dependency. 
**Variable used:** `ossec_syscheck_whodata_directories_1 => "yes"`
![image](https://user-images.githubusercontent.com/13010397/161130741-2a323845-9873-4a8b-b22c-1523ea468917.png)
- [x] Most of the settings for Syscheck are intended for the Wazuh agent side, not Manager.
- [x] Variables that cause errors during deployment
- ossec_syscheck_report_changes_directories_1
- ossec_syscheck_max_eps
![image](https://user-images.githubusercontent.com/13010397/161133016-5abdaf48-43df-475f-b02f-5af8eab4e0bf.png)
- [x] Variable `configure_syscheck` when exists, doesn't write `syscheck` block in `ossec.conf`
With the setting set to "yes", there's no `syscheck` block.
![image](https://user-images.githubusercontent.com/13010397/161133800-f782df1d-3fc1-4cea-a1ad-d0320ae83a88.png)
Without the setting the `syscheck` block is added.
![image](https://user-images.githubusercontent.com/13010397/161133920-0829e3e7-c0dd-4cf7-947f-8e776bc8f804.png)
- [x] Variables have no effect. 
Deleting the following variables from `wazuh-manager.pp` doesn't change anything.
```
ossec_syscheck_process_priority
ossec_syscheck_synchronization_enabled
ossec_syscheck_synchronization_interval
ossec_syscheck_synchronization_max_eps
ossec_syscheck_synchronization_max_interval
```

**Comment by teddytpc1** [comment]
Parameter `ossec_syscheck_report_changes_directories_1` and `ossec_syscheck_max_eps` does not exist in the repo for Manager.

**Comment by teddytpc1** [comment]
Parameter `configure_syscheck` value must be `true` instead of `"true"`

**Comment by teddytpc1** [comment]
>Variables have no effect.

This is the same behavior in v4.2.6. Should be corrected.

**Comment by teddytpc1** [comment]
Regarding `auditd` package, the correct name is `audit`. This should be updated in `audit.pp` and `manager.pp`.

**Comment by teddytpc1** [comment]
The `auditd` package issue was resolved in this [PR](https://github.com/wazuh/wazuh-puppet/pull/481).
