### ISSUE TITLE
Vulnerability detector variables have no effects, have errors, and don't work as expected, 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-puppet#465]
# Description
## Class 
Manager
## Behavior
- [x] `min_full_scan_interval` setting error
The setting was added as part of this epic https://github.com/wazuh/wazuh/issues/7749 intended to be released in 4.3. 
![image](https://user-images.githubusercontent.com/13010397/161135498-f2c625d0-24e5-4ab3-abce-8479174180b4.png)
- [x] Variable `vulnerability_detector_provider_redhat_os => ['7','8']`, doesn't write the OS version like other providers.
![image](https://user-images.githubusercontent.com/13010397/161136434-f2ac004c-c704-4372-873b-9f6e95c7647e.png)
- [x] Configuration for `Arch Linux` is missing. There's no variable to set `Arch Linux` provider
- [x] Configuration for `ALAS Linux` is missing. There's no variable to set `ALAS Linux` provider
- [x] Configuration for `Windows` is missing. There's no variable to set `Windows` provider
- [x] Variable `configure_vulnerability_detector` when exists, doesn't write `vulnerability-detector` block in `ossec.conf`
There's no block `<vulnerability-detector>`
![image](https://user-images.githubusercontent.com/13010397/161136100-fcad5a2b-b930-4a23-9dd1-822fddfe3f7d.png)
The block is written once the setting is deleted
![image](https://user-images.githubusercontent.com/13010397/161136310-daef3fff-3a21-40cd-94e3-ad4721c78add.png)
- [x] Vulnerability-detector variables have no effect.
```
vulnerability_detector_provider_canonical
vulnerability_detector_provider_debian
vulnerability_detector_provider_redhat
vulnerability_detector_provider_nvd
vulnerability_detector_provider_nvd_os
```

**Comment by teddytpc1** [comment]
>  Variable vulnerability_detector_provider_redhat_os => ['7','8'], doesn't write the OS version like other providers.

It should be added within this [if](https://github.com/wazuh/wazuh-puppet/blob/4.3/templates/fragments/_vulnerability_detector.erb#L28).

**Comment by teddytpc1** [comment]
Parameter `configure_vulnerability_detector` default value is `true`. It must be set without double quotes.

**Comment by teddytpc1** [comment]
> Vulnerability-detector variables have no effect.

These variables work only if the `configure_vulnerability_detector` is set to `true`. When it is configured correctly, this is the result:
![image](https://user-images.githubusercontent.com/33964202/161608410-386984c7-b048-4637-9a53-1c81ebab87ba.png)

**Comment by teddytpc1** [comment]
Parameter `min_full_scan_interval` was not added to version 4.3.0 yet.

**Comment by teddytpc1** [comment]
The VD providers were added in this PR #487.
>Configuration for Arch Linux is missing. There's no variable to set Arch Linux provider
 Configuration for ALAS Linux is missing. There's no variable to set ALAS Linux provider
 Configuration for Windows is missing. There's no variable to set Windows provider
