### ISSUE TITLE
SCA variables have no effects and errors. 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-puppet#466]
# Description
## Class
Agent
## Behavior
- [x] The following variables show errors during deployment
```
sca_amazon_enabled
sca_amazon_scan_on_start
sca_amazon_interval
sca_amazon_skip_nfs
sca_amazon_policies
```
![image](https://user-images.githubusercontent.com/13010397/161141411-3ac70480-094b-4b51-9770-ef3b6f34f484.png)
- [x] The following variables have no effect on the ossec.conf file.
```
sca_rhel_enabled
sca_rhel_scan_on_start
sca_rhel_interval
sca_rhel_skip_nfs
sca_rhel_policies
```
- [x] The variable `configure_sca` when exists, doesn't write `sca` block in `ossec.conf`
No sca configuration block in Buster agent
![image](https://user-images.githubusercontent.com/13010397/161142119-5f06f863-1d82-4167-877b-bdf8d62ecf23.png)
![image](https://user-images.githubusercontent.com/13010397/161142236-8f6c5151-dd52-4f8b-bc5f-29acba95d9ee.png)
Block written after deleting the setting
![image](https://user-images.githubusercontent.com/13010397/161142472-a64e85e4-9c69-4225-8843-1ae59030a79a.png)
![image](https://user-images.githubusercontent.com/13010397/161142304-f3e2575c-4416-40e6-9861-00c59fd473ab.png)
- [x] Variable `sca_else_policies => ["policy.yml"]` corrupts `ossec.conf` file
![image](https://user-images.githubusercontent.com/13010397/161142823-f926a0f9-be29-4379-abe2-4d5ade399b79.png)

**Comment by teddytpc1** [comment]
The `sca_rhel` variables behavior is the same in `v4.2.6`.

**Comment by teddytpc1** [comment]
The `configure_sca` variable must be configured as `configure_sca => true` instead of `configure_sca => "true"` to take effect.

**Comment by teddytpc1** [comment]
Regarding `sca_else_policies` the `templates/fragments/_sca.erb` template does not contain the `policies` tag closure. It must be added to correct it, e.g.:
```
  <% if !@sca_else_policies.empty? -%>
  <policies>
  <% @sca_else_policies.each do |policy| -%>
      <policy><%= policy %></policy>
  <%- end -%>
  </policies>
  <policies>
  <%- if @debian_additional_templates == 'yes' -%>
    <policy>cis_debianlinux7-8_L1_rcl.yml</policy>
    <policy>cis_debianlinux7-8_L2_rcl.yml</policy>
  <%- end -%>
  </policies>
  <%- end -%>
```

**Comment by MiguelazoDS** [comment]
Hi @teddytpc1, 

I couldn't see any changes in the `ossec.conf` file nor the puppet console output using the `sca_rhel` variables.

**Comment by teddytpc1** [comment]
PR #486 was created to fix the SCA policies tag.

**Comment by teddytpc1** [comment]
The `sca_rhel_*` variables will only take effect if the OS is a RedHat distribution.
