### ISSUE TITLE
Misc variables have no effect, have errors, and don't work as expected (rootcheck, api, cis_cat, osquery, syslog)

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-puppet#467]
# Description
## Class
- Manager: API, CIS_CAT, Syslog
- Agent: Rootcheck, CIS_CAT
## Behavior
- [x] The following `Syslog` variables have no effect
```
syslog_output_level
syslog_output_port
syslog_output_server
syslog_output_format
```
- [x] The following `configure_<module>` variables don't write the ossec.conf file.
```
configure_wodle_cis_cat
configure_wodle_osquery
configure_rootcheck
```
- CIS_CAT
With `configure_wodle_cis_cat`
![image](https://user-images.githubusercontent.com/13010397/161145994-23ee04cf-a45f-4049-9ac8-d97bc778a0b3.png)
![image](https://user-images.githubusercontent.com/13010397/161146183-6da9b308-7f69-423b-9381-81ec930dbebe.png)
Without `configure_wodle_cis_cat`
![image](https://user-images.githubusercontent.com/13010397/161146248-e505deda-7aa8-4458-895e-f316e14b596b.png)
![image](https://user-images.githubusercontent.com/13010397/161146308-5251318c-d0b1-441d-ada8-89331429d66e.png)
- Osquery
With `configure_wodle_osquery`
![image](https://user-images.githubusercontent.com/13010397/161146605-8b844a22-81e9-442a-865d-c0dae6846379.png)
![image](https://user-images.githubusercontent.com/13010397/161146669-b9e0ac86-1a5c-4015-bd18-4e190f11dfab.png)
Without `configure_wodle_osquery`
![image](https://user-images.githubusercontent.com/13010397/161146785-85d9f9ce-558d-465b-9641-e2a0a0bd94b8.png)
![image](https://user-images.githubusercontent.com/13010397/161146852-a73d07d9-915b-40d7-a82b-9a70a5cffe78.png)
- Rootcheck
With `configure_rootcheck`
![image](https://user-images.githubusercontent.com/13010397/161146991-ff888666-ff20-4d20-9f62-6d4428186c19.png)
![image](https://user-images.githubusercontent.com/13010397/161147123-3239aac6-54f2-4b54-a322-61e601b0c200.png)
Without `configure_rootcheck`
![image](https://user-images.githubusercontent.com/13010397/161147191-944583aa-fd3e-4b4c-9dfa-c07cfb1f18a7.png)
![image](https://user-images.githubusercontent.com/13010397/161147528-39a028b0-46a4-465e-b3bf-a7b7764196ca.png)

**Comment by MiguelazoDS** [comment]
Hi @alberpilot, 

I forgot to mention the error with the variable `wazuh_api_cors_allow_headers`, it is now added to the issue. All the other issues reported were a consequence of misuse. Setting `true` (without quotes) solved the issue.

**Comment by teddytpc1** [comment]
`Syslog` varialables were updated in the document.

**Comment by teddytpc1** [comment]
These variables write in `ossec.conf` only if they are set to `true` (without quotes):
```
configure_wodle_cis_cat
configure_wodle_osquery
configure_rootcheck
```
The variables type was added to the document.
