### ISSUE TITLE
The `ossec_service_provider` variable specified in the documentation are not working for the Wazuh manager and agent deployment

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-puppet#468]
### Description

After doing some testing of the Wazuh cluster deployment by using Puppet, we identified some issues in the variables specified in the documentation. The `ossec_service_provider` variable causes an error when it is used in a manifest to deploy either a Wazuh manager as well as a Wazuh agent. Here is a snippet of the error:

![image](https://user-images.githubusercontent.com/5703274/161181255-f748db17-e28c-40fe-b324-f97a1fc2ed4f.png)

**Comment by alberpilot** [comment]
@teddytpc1 requested to content team to remove this variable. I proceed to close this issue.
