### ISSUE TITLE
puppetlabs/concat 4.1.1 is incompatible with wazuh/puppet 2.0.22

### ISSUE THREAD

**Issue by jhowe-uw** [wazuh/wazuh-puppet#48]
Using concat 4.1.1 on ubuntu xenial, the puppet run fails:

It appears concat added some functionality in 4.1.0 that breaks wazuh-puppet runs

Rolling back to concat 4.0.1 works.

2017-11-16 12:32:30 -0800 Puppet (err): Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'format' at /etc/puppetlabs/code/environments/feature_ubuntu_support/modules/concat/manifests/init.pp:94 on Concat_file[ossec.conf] at /etc/puppetlabs/code/environments/feature_ubuntu_support/modules/concat/manifests/init.pp:94 on node

Using the following in Puppetfile:

wazuh-wazuh (v2.0.22)
puppet-selinux (v1.3.0) 
puppetlabs-apt (v4.4.0) 
puppetlabs-concat (v4.0.1)
puppetlabs-stdlib (v4.22.0)
stahnma-epel (v1.3.0)

From https://forge.puppet.com/puppetlabs/concat/changelog

Supported Releases 4.1.0

Summary

This release is a rollup of changes. The most notable change being the addition of the 'format' attribute which allows output in JSON and YAML formats, and the 'force' attribute which if true forces a merge of duplicate keys for these formats.

Features

**- Format and force attributes added.**
- Deprecated is_string in favour of puppet language.
- End of Life Ubuntu releases removed as supported.
- Debian 9 added and Debian 6 removed as supported.
- 

Bugfixes

- (MODULES-4359) Fix native types so they can be used directly.
- Update to tests to handle errors containing quote marks.
- Update to tests to follow rspec-puppet pattern.

Thanks!

**Comment by mjflve** [comment]
Hi @jhowe-uw,

Can you please tell us the version of the puppet server you're using?, I'm trying to replicate this issue without success so far.

Thanks in advance.

**Comment by jhowe-uw** [comment]
Puppet CE on Debian Jessie

$ cat /etc/debian_version
8.9

ii  puppet-agent                    5.3.3-1jessie                      amd64        The Puppet Agent package contains all of the elements needed to run puppet, including ruby, facter, hiera and mcollective.
ii  puppet5-release                 5.0.0-1jessie                      all          Release packages for the Puppet5 repository
ii  puppetdb                        5.1.3-1jessie                      all          no description given
ii  puppetdb-termini                5.1.3-1jessie                      all          no description given
ii  puppetexplorer                  2.0.0-62                           all          web frontend for PuppetDB
ii  puppetserver                    5.1.4-1jessie                      all          no description given

**Comment by mjflve** [comment]
Hi @jhowe-uw,

Sorry for the late reply. After several tests, this seems to be more related to the concat module, this should be fixed by using `puppet generate types`, on the worst case by restarting the puppet server, some references to this issue can be found here:

https://tickets.puppetlabs.com/browse/MODULES-5802
https://tickets.puppetlabs.com/browse/MODULES-5861

Let us know if it helps, thanks.

Regards,
