### ISSUE TITLE
Fix the $manage_repos attribute.

### ISSUE THREAD

**Issue by pillarsdotnet** [wazuh/wazuh-puppet#50]
We need to install packages outside of the standard repos.

**Comment by mjflve** [comment]
Hi @pillarsdotnet,

Thanks for your contribution, let us review it and merge.

Regards,

**Comment by pillarsdotnet** [comment]
Also, I have some minor fixes that allow this module to be used with AmazonLinux.

**Comment by mjflve** [comment]
Hi @pillarsdotnet 

Sorry for the late reply, taking into account this issue I made some changes to this module in order to set a custom repository URL before the package installation, please take a look:

https://github.com/wazuh/wazuh-puppet/tree/set_repository

We can include these changes with your Amazon Linux fixes, just let us know. Thanks!

Best regards,

**Comment by pillarsdotnet** [comment]
Feel free to incorporate my AmazonLinux fixes, but the "custom repository URL" feature won't help me.

Package resources may be declared only once.  Therefore, two modules which depend on the same package cannot both declare that package resource.  (At least) one of them has to defer package installation.  The usual way to manage that deferral is to support a boolean attribute, usually called `$manage_package` which defaults to true but skips package installation if set to false.

Offering to install from a custom repository may be useful, but it doesn't address the underlying problem.

Also, we have a proprietary method of transferring our wazuh (and other custom-compiled) packages; they're not stored in a traditional repository.

**Comment by jlruizmlg** [comment]
Let me jump into the conversation, in the manifest client.pp and server.pp, we have a variable to disable the repositories:
https://github.com/wazuh/wazuh-puppet/blob/master/manifests/client.pp#L26
https://github.com/wazuh/wazuh-puppet/blob/master/manifests/server.pp#L34

With ```$manage_repo => false```, if your custom packages have the same name than the wazuh packages, the module should work without problems.

The module verifies that you have one wazuh-manager or wazuh-agent installed (no matter which process you did to install them) and then only apply the configurations that you define in your manifest.

Your actual changes broke the normal installation in a standard installations with errors like

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Could not find resource 'Package[wazuh-agent]' for relationship from 'Class[Wazuh::Repo]' on node puppet-centos7.localdomain
```

**Comment by pillarsdotnet** [comment]
Unfortunately, the `$manage_repo` variable only controls whether the `epel` repo is installed. See [client.pp lines 58-65](https://github.com/wazuh/wazuh-puppet/blob/master/manifests/client.pp#L58) and [server.pp lines 80-87](https://github.com/wazuh/wazuh-puppet/blob/master/manifests/server.pp#L80). The subsequent `package` resource is declared whether `$manage_repo` is true or false.  See [client.pp lines 66-68](https://github.com/wazuh/wazuh-puppet/blob/master/manifests/client.pp#L66) and [server.pp lines 92-94](https://github.com/wazuh/wazuh-puppet/blob/master/manifests/server.pp#L92). And if a `package` resource with the same name is declared elsewhere, (in my case, with `provider => 'rpm'`), the entire puppet run aborts with a duplicate resource error.

However, if my patch is applied with `$manage_package => false`, and something like the following puppet code is invoked elsewhere in the same run, the puppet run completes successfully:
```
package { 'wazuh-agent':
  provider => 'rpm',
  source   => '/tmp/wazuh-agent-3.0.0-beta6.rpm',
}
```

I will work on a minimal test manifest that demonstrates this capability.

**Comment by jlruizmlg** [comment]
Hi @pillarsdotnet , the variable ```$manage_repo``` controls the packages repositories, you have two 
```
  $manage_repo                 = true,
  $manage_epel_repo            = true,
```
The indent maybe is not correct but $manage_repo controls all this block

```
if $manage_repo {
class { 'wazuh::repo': redhat_manage_epel => $manage_epel_repo }
if $::osfamily == 'Debian' {
          Class['wazuh::repo'] -> Class['apt::update'] -> Package[$agent_package_name]
        } else {
          Class['wazuh::repo'] -> Package[$agent_package_name]
        }
      }
      package { $agent_package_name:
ensure => $agent_package_version
      }
    }
```

**Comment by pillarsdotnet** [comment]
I'll re-indent and write a test.

**Comment by pillarsdotnet** [comment]
@jlruizmlg -- The indentation is correct.  See #55
