### ISSUE TITLE
Support agents on SUSE

### ISSUE THREAD

**Issue by genebean** [wazuh/wazuh-puppet#511]
According to https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html, the agent can be installed via zypper. Please enable this in the module as right now it throws `This ossec module has not been tested on your distribution` when applied to a SLES host.

**Comment by rauldpm** [comment]
Hello @genebean 

Sorry for the late response, thanks for the request, we added the issue to our roadmap to develop and test it, thanks!

Regards, Raúl.

**Comment by vcerenu** [comment]
Checking for variables within manifests to add agent installation.
