### ISSUE TITLE
Review and fix for the exec resource declarations in wazuh::indexer, wazuh::dashboard and wazuh::filebeat_oss

### ISSUE THREAD

**Issue by vaskosmihaylov** [wazuh/wazuh-puppet#512]
# Description
 ## Classes
 Indexer, Dashboard, Filebeat
 
 ## Behavior
 * [ ]  Improving the exec resources in the aforementioned classes 
 
[Indexer code](https://github.com/wazuh/wazuh-puppet/blob/cabc30e8bff40382edbe85a932dd79ebed816e82/manifests/indexer.pp#L53-L97)

[Dashboard code](https://github.com/wazuh/wazuh-puppet/blob/0d2ebbff2ba5e7e1c459ce781facd6738444da96/manifests/filebeat_oss.pp#L43-L59)

 [Filebeat related code](https://github.com/wazuh/wazuh-puppet/blob/0d2ebbff2ba5e7e1c459ce781facd6738444da96/manifests/filebeat_oss.pp#L43-L59)
 
The above exec declarations run on every puppet run even though the certificates, folders and configuration are already added:
 
![wazuh-exec](https://user-images.githubusercontent.com/24459819/175023978-fe3db1fb-c2bf-4ebd-ba71-0cee5e37859c.png)

* [ ]  Also, the following exec is incorrect:

``` exec { 'Insert line limits':
    path    => '/usr/bin:/bin/',
    command => "echo 'elasticsearch - nofile  65535\nelasticsearch - memlock unlimited' >> /etc/security/limits.conf",
    require => Package[$indexer_package],
  }
```

It echoes the user **elasticsearch** in the /etc/security/limits.conf while all the wazuh-indexer directories are owned by **wazuh-indexer** user and also running on every puppet run it add the line again and again:

```
grep elasticsearch /etc/security/limits.conf | wc -l
20
```

## Solution

Our team would like to create a PR request, fix and improve the exec declaration and submit a merge request, however before proceeding further we would like to know if this is applicable for the Wazuh team and also if our merge request will be approved.

**Comment by vcerenu** [comment]
Hello @vaskosmihaylov 

We have analyzed and tested the PR that you sent us and it is already merged into the development branch of the current version, so it will be available in the next Wazuh release.

Thank you very much for the development and if you have any questions or ideas, do not hesitate to contact us.
