### ISSUE TITLE
Missing template for Wazuh indexer configuration

### ISSUE THREAD

**Issue by poloz-lab** [wazuh/wazuh-puppet#527]
Hello Wazuh team,

The configuration file `/etc/wazuh-indexer/opensearch.yml` doesn't match with parameters set in Wazuh indexer class.

I'm using the 4.3.6 module version on Debian 10 machines.

In the Wazuh indexer class there are some configuration variables but none of them are used in the puppet module.
There is no template for  `/etc/wazuh-indexer/opensearch.yml`.

Templates for elastic search and opensearch configuration files has been removed with Wazuh 4.3.0 but no template was created for Wazuh indexer.

I can work on a PR if you confirm that a template is missing.

**Comment by c-bordon** [comment]
Hello, we have tested your PR and we have approved and merged it, thank you very much for your participation
