### ISSUE TITLE
Wazuh repo management missing in Wazuh dashboard

### ISSUE THREAD

**Issue by poloz-lab** [wazuh/wazuh-puppet#528]
Hello Wazuh team,

It should be great if the Wazuh dashboard class had a manage repo option as the Wazuh indexer class.

When the Wazuh dashboard is not installed on the same machine as the Wazuh manager or the Wazuh indexer, the Wazuh repo is not configured and the package can't be installed. If we add the repo outside of the class, we have to fix the order of the resources declared in the class and it's not convenient.

I can work on a PR if you think that the option is relevant.

**Comment by vcerenu** [comment]
Hello @poloz-lab 

This case that you raise seems relevant to us, we can add it to our backlog to review it in future Wazuh releases.

In case you want to collaborate with a PR that includes the necessary changes, we will be very grateful and we will review it to add it in the next release.

**Comment by poloz-lab** [comment]
@vcerenu I think that PR #529 is ready.
Not sure about the base branch and the project organisation.
Feel free to review / comment.

**Comment by vcerenu** [comment]
Hi @poloz-lab 

I'm testing that PR with all deploy options and in case that we haven't issues we will merge it.

Thanks for the effort and work!

**Comment by poloz-lab** [comment]
Hi @vcerenu ,

I marked this PR as draft today because I have a doubt about the necessity of the require wazuh::repo instruction. An include should be enough, as the dependency is explicitly defined in the if else statement.

Sorry for the inconvenience. I'm gonna test it tomorrow
