### ISSUE TITLE
 Missing template for Wazuh dashboard configuration 

### ISSUE THREAD

**Issue by le-ya** [wazuh/wazuh-puppet#534]
Hello Wazuh team,

The configuration file /etc/wazuh-dashboard/opensearch_dashboards.yml doesn't match with parameters set in Wazuh dashboard class.

I'm using the 4.3.6 module version on Debian 10 machines.

In the Wazuh dashboard class there are some configuration variables but only two  of them are used in the puppet module.
There is no template for /etc/wazuh-dashboard/opensearch_dashboards.

We are working on a PR.

**Comment by poloz-lab** [comment]
The API configuration `/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml` is missing too

**Comment by vcerenu** [comment]
Hello @le-ya 

We have merged the PR associated with this issue, it will be present in the next Wazuh release

Thanks for the development @poloz-lab
