### ISSUE TITLE
Wazuh keeps trying to install new certificates

### ISSUE THREAD

**Issue by jurgenmehja** [wazuh/wazuh-puppet#535]
Hello Wazuh team,
the module doesn't check if the certificate's directory exists before trying to copy them:
`Error: /Stage[main]/Wazuh::Indexer/Exec[Copy Indexer Certificates]/returns: change from 'notrun' to ['0'] failed: 'mkdir /etc/wazuh-indexer/certs              && cp /tmp/wazuh-certificates/indexer.pem  /etc/wazuh-indexer/certs             && cp /tmp/wazuh-certificates/indexer-key.pem  /etc/wazuh-indexer/certs             && cp /tmp/wazuh-certificates/root-ca.pem  /etc/wazuh-indexer/certs             && cp /tmp/wazuh-certificates/admin.pem  /etc/wazuh-indexer/certs             && cp /tmp/wazuh-certificates/admin-key.pem  /etc/wazuh-indexer/certs             && chown wazuh-indexer:wazuh-indexer -R /etc/wazuh-indexer/certs             && chmod 500 /etc/wazuh-indexer/certs             && chmod 400 /etc/wazuh-indexer/certs/*' returned 1 instead of one of [0] (corrective)`
`Error: /Stage[main]/Wazuh::Dashboard/Exec[Copy Dashboard Certificates]/returns: change from 'notrun' to ['0'] failed: 'mkdir /etc/wazuh-dashboard/certs              && cp /tmp/wazuh-certificates/dashboard.pem  /etc/wazuh-dashboard/certs             && cp /tmp/wazuh-certificates/dashboard-key.pem  /etc/wazuh-dashboard/certs             && cp /tmp/wazuh-certificates/root-ca.pem  /etc/wazuh-dashboard/certs             && chown wazuh-dashboard:wazuh-dashboard -R /etc/wazuh-dashboard/certs             && chmod 500 /etc/wazuh-dashboard/certs             && chmod 400 /etc/wazuh-dashboard/certs/*' returned 1 instead of one of [0] (corrective)`
`Error: /Stage[main]/Wazuh::Filebeat_oss/Exec[Copy Filebeat Certificates]/returns: change from 'notrun' to ['0'] failed: 'mkdir /etc/filebeat/certs              && cp /tmp/wazuh-certificates/server.pem  /etc/filebeat/certs/filebeat.pem             && cp /tmp/wazuh-certificates/server-key.pem  /etc/filebeat/certs/filebeat-key.pem             && cp /tmp/wazuh-certificates/root-ca.pem  /etc/filebeat/certs             && chown root:root -R /etc/filebeat/certs             && chmod 500 /etc/filebeat/certs             && chmod 400 /etc/filebeat/certs/*' returned 1 instead of one of [0] (corrective)
`

**Comment by poloz-lab** [comment]
Hi @jurgenmehja ,

I had the same problem but PR #516 fixes this problem.
It has been merged in branch "4.3".

**Comment by jurgenmehja** [comment]
Just saw it, great!
