### ISSUE TITLE
Change permission for filebeat.yml

### ISSUE THREAD

**Issue by YannickTektek** [wazuh/wazuh-puppet#540]
As the keystore is not used by the module, at least hide the filebeat's credentials to other users.  (Username and Password) in the config.

**Comment by vcerenu** [comment]
Hello @YannickTektek 

This issue has been worked on by @poloz-lab in the following PR
https://github.com/wazuh/wazuh-puppet/pull/541

We will review it and when we have merged this change we will be notifying you in this issue
