### ISSUE TITLE
JVM memory option doesn't modify the JVM options

### ISSUE THREAD

**Issue by poloz-lab** [wazuh/wazuh-puppet#546]
The parameter `jvm_options_memmory` in `wazuh::indexer` doesn't modify the JVM options in `/etc/wazuh-indexer/jvm.options`.

I'm using the branch 4.3 with Puppet 6.27.0 on a Debian 10 machine.

**Comment by vcerenu** [comment]
Hello @poloz-lab

Thanks for your patience and contribution. We are working hard to review all the requests as soon as possible. Currently, we are reviewing the PR that contains these changes
