### ISSUE TITLE
Incorrect agent versioning on Windows

### ISSUE THREAD

**Issue by Rewerson** [wazuh/wazuh-puppet#561]
Current value of `$agent_package_version = '4.3.7-1'` is suitable only for Linux packages.
When using on Windows hosts, there are attempts to reinstall wazuh agent on every puppet run:
`notice 
/Stage[main]/Wazuh::Agent/Package[Wazuh Agent]/ensure
ensure changed '4.3.7' to '4.3.7-1' (corrective)`

**Comment by c-bordon** [comment]
Hi Rewerson, I am doing tests on the inconvenience that is presented to you, I will be answering you with the solution as soon as possible
