### ISSUE TITLE
Change default port for Wazuh Dashboard

### ISSUE THREAD

**Issue by poloz-lab** [wazuh/wazuh-puppet#564]
The default value for the listening port to Wazuh web interface in the `wazuh::dashboard` class (5601) is not the value found in Wazuh documentation (403) [here](https://documentation.wazuh.com/4.3/installation-guide/wazuh-dashboard/step-by-step.html) and [here](https://documentation.wazuh.com/4.3/getting-started/architecture.html#required-ports).

When I use the Puppet module without specifying any port, I expect to have the default ones.

**Comment by fcaffieri** [comment]
Hello @poloz-lab, Thanks for the contribution. I'll be doing tests and reviewing the PR. As soon as I have a conclusion, I'll come back with an answer.
