### ISSUE TITLE
Use the default credentials to connect the dashboard to the server API

### ISSUE THREAD

**Issue by poloz-lab** [wazuh/wazuh-puppet#566]
The `wazuh-dashboard` package use the `wazuh-wui:wazuh-wui` default credentials to access the server API.
But in the default parameters from the `wazuh::dashboard` class there is `foo:bar`.

When I don't specify the credentials to the `wazuh::dashboard` class, I expect it to use the default ones.

**Comment by c-bordon** [comment]
Hi poloz-lab, I'm working on the proposed change, currently we need to make some additional changes to yours, I'm working on them to be integrated in version 4.4.0 of Wazuh

**Comment by c-bordon** [comment]
I found a bug in the 4.4 update with the 4.3 files:
```
root@ubuntu-focal-2:~# puppet agent -t
Info: Using environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::archive for ubuntu-focal-2 (file: /etc/puppetlabs/code/environments/production/modules/wazuh/manifests/filebeat_oss.pp, line: 63, column: 3) on node ubuntu-focal-2
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

```

**Comment by poloz-lab** [comment]
Hi @c-bordon ,

The PR #545 introduced a new dependency to the "archive" module.
Do you have installed this module ?
