### ISSUE TITLE
Use https instead of http in default Wazuh API URL

### ISSUE THREAD

**Issue by poloz-lab** [wazuh/wazuh-puppet#568]
The `wazuh::dashboard` class use http for the server API URL configuration in its default parameters. The [Wazuh documentation](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/step-by-step.html#starting-the-wazuh-dashboard-service) use https.

**Comment by c-bordon** [comment]
Hello, we have tested your PR and we have approved and merged it, thank you very much for your participation
