### ISSUE TITLE
How to use custom ossec.conf with Puppetfile?

### ISSUE THREAD

**Issue by maltfield** [wazuh/wazuh-puppet#57]
Hi,

What is the proper way to define a custom ossec.conf file with this puppet module?

Our org is using r10k to mange this puppet module (using a Puppetfile). Therefore, if we edit the wazuh/templates/wazuh_manager.conf.erb file directly, our changes would be lost when r10k downloads a new version of this puppet module from github.

Therefore, we're using a custom/wrapper Private Component module called 'privatewazuhserver' to call the 'wazuh::server' class & manage our custom templates.

For managing /var/ossec/etc/rules/local_rules.xml, I was successfully able to create a template in this private component module & reference it using the 'local_rules_template' variable. In this case, I set the 'local_rules_template' variable to 'privatewazuhserver/local_rules.xml.erb', which we simply put in a 'templates' directory in our 'privatewazuhserver' module on our internal github.

But how can this be done with ossec.conf? Is there an equivalent to 'local_rules_template' for the 'ossec.conf' file?

**Comment by mjflve** [comment]
Hi @maltfield,

Sorry for the late reply. You could use the vars shipped with this modules to control settings like syscheck, rootcheck, openscap among others in the Wazuh agent and the Wazuh manager as well. I'm wondering what settings/tags are you trying to configure, thanks!

Best regards,

**Comment by Zenidd** [comment]
Hello @maltfield,

It seems that they have given you a clue as to how to solve your problem so i'm closing this issue. If you have any other do not hesitate to open another issue.

Kind regards,

Juan Pablo Sáez
