### ISSUE TITLE
Actualize Wazuh dashboard template for API connection settings

### ISSUE THREAD

**Issue by poloz-lab** [wazuh/wazuh-puppet#570]
The template for the configuration file of the server API connection on the dashboard (`/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml`) is not up to date.

Only commented lines are changing so it's not important.

**Comment by c-bordon** [comment]
Hello poloz-lab, thank you for your contribution, in this case, we made a new [PR](https://github.com/wazuh/wazuh-puppet/pull/584)  with the latest version of this file so that the template is updated with respect to this [PR](https://github.com/wazuh/wazuh-kibana-app/pull/4378)
