### ISSUE TITLE
Not able to change the credentials used to connect the dashboard to the indexer

### ISSUE THREAD

**Issue by poloz-lab** [wazuh/wazuh-puppet#572]
As the credentials are stored in the keystore `/usr/share/wazuh-dashboard/config/opensearch_dashboards.keystore`, the dashboard uses the default `kibanaserver:kibanaserver` to be authenticated on the indexer.

The module is not able to configure other credentials.

**Comment by c-bordon** [comment]
We have tested and approved your [PR](https://github.com/wazuh/wazuh-puppet/pull/573), thank you very much for your contribution
