### ISSUE TITLE
Script indexer-security-init.sh is re-executed when it's not needed

### ISSUE THREAD

**Issue by poloz-lab** [wazuh/wazuh-puppet#574]
The initialisation script for indexer security (`/usr/share/wazuh-indexer/bin/indexer-security-init.sh`) is executed even if the security is already initialized (in some case).

This happened to me when I've re-created a machine and used an older database.
This has erased my user credentials by resetting it to defaults.

In the [current code](https://github.com/wazuh/wazuh-puppet/blob/99c0ddd8d823709d48b4007bd7657334f15c39bc/manifests/indexer.pp#L140), the execution of the script is linked to the installation of the `wazuh-indexer` package.
So when I re-install the package but I keep the database, the initialisation script is still executed.
This is not the expected behaviour. The script must be executed only once, to initiate the database.

Working on a PR.

**Comment by c-bordon** [comment]
Hello poloz-lab, we have reviewed and approved your PR, thank you very much for your contribution
