### ISSUE TITLE
Support for Wazuh 3.x

### ISSUE THREAD

**Issue by eborned** [wazuh/wazuh-puppet#59]
Anyone working on supporting the 3.x version of Wazuh that 'just' came out? I'm a new user and tried to use the Puppet module to deploy to my machines. This works, but the 2.x agent is installed. Also, I think that there are some configuration changes required to support 3.x fully. Support for the new 'integration' 
 configuration has to be added.

Maybe we can start a branch to extend the current module to support 3.x by using a version flag?
$wazuh_version = 3
And keep version 2 the default (for now)

**Comment by jlruizmlg** [comment]
Hi @eborned, yes is in our roadmap the integration with 3.x, and we hope to finish in this week the implementation.

We will keep you posted.

**Comment by eborned** [comment]
If there is a test version that I can have a look at: let me know. I'm currently still in the deployment stage, so bugs and other problems won't be that big of a problem for me.

**Comment by jlruizmlg** [comment]
@eborned We will try to release some code this week, we will let you know :)

**Comment by ajurjevi** [comment]
Any news for Wazuh 3.x support?

**Comment by vnikitov** [comment]
Can we expect support for Wazuh 3.x to be released soon?

**Comment by jlruizmlg** [comment]
Hi all, we have a new branch 3.x-devel where we are updating the code to upgrade to 3.x version, We are hoping to merge the code next week.

**Comment by eborned** [comment]
Great news. If you need me to test anything, let me know!

**Comment by jlruizmlg** [comment]
hi @eborned all test are more than welcome 😀

**Comment by jlruizmlg** [comment]
Hi @eborned thanks for the pull request, something that we can do is verify if we have integrator enabled or not in our configuration:

 **Integrator enabled**

 **_/var/ossec/bin/ossec-control status_**
wazuh-clusterd not running...
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted is running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd is running...
wazuh-modulesd is running...
wazuh-db is running...
**_ossec-integratord is running..._**
ossec-authd is running...


In the manifests/integration.pp we could do something like that:

```
  exec { 'Enable_Integrator':
    command => '/var/ossec/bin/ossec-control enable integrator',
    onlyif  =>  [ '/var/ossec/bin/ossec-control status | grep integrator | grep -v grep' ]
  }
}
```

What do you think??

**Comment by SitoRBJ** [comment]
Hello everyone,

The PR #85 resolves the update.

Thank you very much for your contribution, we proceed to close the issue. 

Best regards,

Alfonso Ruiz-Bravo
