### ISSUE TITLE
Fresh install: /var/ossec/etc/shared/agent.conf missing hence validate_cmd fails.

### ISSUE THREAD

**Issue by elisiano** [wazuh/wazuh-puppet#6]
In a fresh installation (tested this on `CentOS 7` with `puppet 3.8.7`, `wazuh-manager-2.0-1.el7.x86_64.rpm` ) the puppet run fails to validate the shared agent conf file because absent.

The node includes only `wazuh::server` class from this module.

Just by touching the file fixes this (after the package is installed). I'm not sure how it behaves on Debian or Windows but if the file is not distributed (even if empty) with the packages this might fails there too.

Before attempting to submit a PR with a simple fix, I'd need more info about what the packages contain on non-centos/redhat systems.

**Comment by jlruizmlg** [comment]
Hi @elisiano, let us take a look, this issue happens under Puppet 4.x as well thanks for let us know.

**Comment by jlruizmlg** [comment]
Hi @elisiano sorry for the delay here, this issue is fixed in the pull request #12, thanks
