### ISSUE TITLE
4.3 branch installs 4.4.0 version

### ISSUE THREAD

**Issue by poloz-lab** [wazuh/wazuh-puppet#616]
PR #609 has introduced the 4.4.0 version in the 4.3 branch.

I expect the 4.3 branch to stay on the 4.3.x versions.

**Comment by rauldpm** [comment]
Hello @poloz-lab 

It's true, we are working on fixing this problem, thanks for the notice.

**Comment by poloz-lab** [comment]
Thank you @rauldpm

**Comment by rauldpm** [comment]
Hello @poloz-lab 

This has been fixed in the https://github.com/wazuh/wazuh-puppet/pull/617 pull request. Thanks again!

**Comment by poloz-lab** [comment]
Thank you Wazuh team !
I can now rebase my old pull requests
