### ISSUE TITLE
enable_wodle_openscap default true or false?

### ISSUE THREAD

**Issue by reliam** [wazuh/wazuh-puppet#62]
Per documentation `enable_wodle_openscap` is false by default: https://documentation.wazuh.com/current/deploying-with-puppet/wazuh-puppet-module/reference-wazuh-puppet/wazuh-agent-class.html#reference-wazuh-agent-class

In the agent/client class it's set to true: https://github.com/wazuh/wazuh-puppet/blob/master/manifests/client.pp#L37

**Comment by jlruizmlg** [comment]
Hi @reliam sorry for the late response, you are right, fixed in the commit 1f2003509b9bc95d208dd790f6f0b7511fb75441
