### ISSUE TITLE
Allow certificates to be defined by file path

### ISSUE THREAD

**Issue by minorOffense** [wazuh/wazuh-puppet#66]
Our servers already have client certs and the ca cert file in place. I’d like to be able to tell the wazuh client and manager to use those files instead of having to pass the raw string value for the certificates to authenticate everyone. 

(If you’re curious we actually reuse the Puppet agent / master certs since they’re already there and validated)

I’m fine writing the functionality just want to make sure it’s soenthing you’d be interested in adding to the module. I’d be adding it to the 3.x dev. 

I should have some code later today for review.

**Comment by jlruizmlg** [comment]
Hi @minorOffense sound perfect!

**Comment by LuisGi93** [comment]
Hi @minorOffense ,
I'm currentlty working in this issue. The work could be followed at the following branch:
https://github.com/wazuh/wazuh-puppet/tree/dev-certificate_by_path

Right now some changes were made to allow the use of the specification of the CA, the cert and cert keys and the manager and client manifest. These changes still need to be tested to verify that they fix this issue.

**Comment by minorOffense** [comment]
Yeah we ran into issues with elastic so I didn’t get to finish implementing this. I’ll poke around the branch to see what’s going on and compare to what I had started.

**Comment by manuasir** [comment]
Solved #112.
