### ISSUE TITLE
Support for Amazon Linux?

### ISSUE THREAD

**Issue by ErmisCat** [wazuh/wazuh-puppet#68]
There is a path to install the RPM packages for Amazon Linux, so I was a little surprised when I pushed out wazuh::client to one of my amazon machines as a test, and it failed because the OS is not supported in params.pp...

Is this something you plan on fixing or should I fork and make my own version?

**Comment by jlruizmlg** [comment]
Hi @ErmisCat it will be supported in wazuh 3.x we are finishing some testing to release the code.

The branch https://github.com/wazuh/wazuh-puppet/tree/3.x-devel can be used to deploy the version 3.3.1.

**Comment by ErmisCat** [comment]
@jlruizmlg great, thank you!

**Comment by ErmisCat** [comment]
`Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Unknown function: 'validate_bool'. (file: /etc/puppetlabs/code/environments/******/modules/wazuh/manifests/client.pp, line: 48, column: 3) on node`

I looked at the metadata.json and puppetlabs/stdlib is in the dependencies, so this is a strange error to have. 

This is the 3.x-devel branch.

**Comment by ErmisCat** [comment]
Using puppet 5.3.5.

I think part of the issue is this syntax in params.pp and repo.pp: 'Linux', 'RedHat':

I forked this, ripped out what I didn't need and fixed any syntax errors for puppet 5 to work cleanly.

I now deploy it successfully with this branch: https://github.com/skio-music/wazuh-puppet/tree/3.x_amazonlinux-dev

Works for Amazon Linux now.

Thanks

**Comment by weavage** [comment]
I believe 'validate_bool' is part of Puppet's stdlib. Based on your error message, it looks like you don't have it installed.

**Comment by LuisGi93** [comment]
Hi @ErmisCat. I have been testing this issue the past week and I was able  to install successfully  the Wazuh agent in Amazon Linux using wazuh::client. I have tested it using Puppet 4.10 and 5.5. I was unable to reproduce the errors related with this issue.

**Comment by jm404** [comment]
Hi @ErmisCat, @weavage 

The Amazon Linux image is being tested in order to guarantee the correct installation in such OS for the new release.

You can check all notices and advances in the [Release 3.9.1_7.1.0](https://github.com/wazuh/wazuh-puppet/issues/123) issue and feel free to share any questions or concerns anytime!

Best regards,

Jose

**Comment by manuasir** [comment]
Done here #128
