### ISSUE TITLE
Wrong openscap profile CentOS 7

### ISSUE THREAD

**Issue by Fabian1976** [wazuh/wazuh-puppet#72]
It looks like the wazuh-agent tries to use the wrong scap profile on CentOS 7. In the params.pp these profiles are used for both CentOS 6 and 7:
```
profiles => [
  'xccdf_org.ssgproject.content_profile_pci-dss',
  'xccdf_org.ssgproject.content_profile_server',
]
```
These are correct for CentOS 6, but for 7 they should be these:
```
profiles => [
  'xccdf_org.ssgproject.content_profile_pci-dss',
  'xccdf_org.ssgproject.content_profile_cjis-rhel7-server',
]
```

You can check it by running this on a CentOS 7 server:
```oscap info /var/ossec/wodles/oscap/content/ssg-centos-7-ds.xml```

**Comment by LuisGi93** [comment]
Hi @Fabian1976,
for Centos 7 we are [currently using](https://github.com/wazuh/wazuh-puppet/blob/3.8/manifests/params.pp#L167):
```
xccdf_org.ssgproject.content_profile_pci-dss,
xccdf_org.ssgproject.content_profile_common
```
Which are the ones that [wazuh uses by default](https://documentation.wazuh.com/3.x/user-manual/capabilities/policy-monitoring/openscap/how-it-works.html#default-policies).

Regards.
