### ISSUE TITLE
Windows agent installation file in root

### ISSUE THREAD

**Issue by Fabian1976** [wazuh/wazuh-puppet#73]
The Windows wazuh-agent installation file, is placed in the root folder of C:. It's not an urgent bug or anything, but a bit "messy".

I will prepare a PR for this.

**Comment by Zenidd** [comment]
Hi @Fabian1976,

Thank you for having taken your time to provide us with your valuable feedback relating to the installation process on windows. 

Your observation is correct; to this day, the windows wazuh-agent installation file keeps being placed in the root folder of C. We look forward to your PR for review and merge.



Again, thank you for helping us improve.

<br></br>
Regards,

Juan Pablo Sáez
