### ISSUE TITLE
Tag for 3.X

### ISSUE THREAD

**Issue by F00ker** [wazuh/wazuh-puppet#80]
Hi,

We'd like to deploy puppet 3.6 on our environment rather than 2.0.21 or 2.0.22.

Could we get a tag for that?

Thanks

**Comment by jesuslinares** [comment]
Hi @F00ker,

We are working on it. I'll let you know when it is ready.

Thanks.

**Comment by jm404** [comment]
Hi @F00ker,

Sorry for the late response,

Wazuh Puppet's latest release is `6.7' so we consider this request obsolete as it's been a long time and you probably updated to a newer version.

You can check our new [Puppet Release](https://github.com/wazuh/wazuh-puppet/tree/v3.9.3_7.2.0) that provides a lot of improvements and features!

Feel free to open a new issue in case you need it.

Best regards,

Jose
