### ISSUE TITLE
Agent ID conflict when using fqdn_rand()

### ISSUE THREAD

**Issue by fluential** [wazuh/wazuh-puppet#83]
When distributing agent keys via puppet, the ids generated by fqdn_rand() are not unique. With large number of hosts there are id conflicts. Wazuh is "old" enough that it does not accept any hashing algorithm which would ensure agent ID uniqueness therefore there has to be a central place where agent IDs are managed
To solve this I've created a simple puppet external node classifier that ensures unique id based on $fqdn https://github.com/fluential/wazuhenc

**Comment by Zenidd** [comment]
Hello @fluential,

first of all, sorry for the late response.

Thanks for your contribution to Wazuh. We really appreciate the effort you've put into this !
Our team will review it and include it in the project as soon as possible. 


<br></br>

Best regards,

Juan Pablo Sáez

**Comment by jm404** [comment]
Hi @fluential,

Sorry for the late response,

We recently removed the `export` method of registration in our Wazuh Puppet module. You can check all the information and discussion related to the deletion of this method in #58 

Best regards

Jose
