### ISSUE TITLE
Update Configuration to New Vulnerability Detector and Indexer

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh-puppet#864]
**Description:**

This issue focuses on updating the configuration settings for the vulnerability detector and indexer modules to align with the new templates. The old configuration for vulnerability detection will be removed, and the settings will be replaced with those described in the following templates:

- [Vulnerability Detector Configuration](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/etc/templates/config/generic/wodle-vulnerability-detection.manager.template)
- [Indexer Configuration](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/etc/templates/config/generic/wodle-indexer.manager.template)

**User Stories:**

- As a system administrator, I want the configuration to be up-to-date with the new vulnerability detection and indexing templates to ensure optimal functionality.
- As a developer, I want to remove the old configuration settings and replace them with the new templates to maintain consistency and improve maintainability.

**Tasks:**

1. Review New Configuration Templates:
   - Examine the provided vulnerability detector and indexer configuration templates thoroughly.

2. Identify Old Configuration Settings:
   - Identify the old configuration settings that need to be removed.

3. Replace Old Settings with New Templates:
   - Implement the new configuration settings from the provided templates.

**Definition of Done:**

- The old configuration settings have been removed.
- The new configuration settings from the provided templates have been implemented.

**Comment by vcerenu** [comment]
AIO Deployment

```
  # Configuration for Vulnerability detection
<vulnerability-detection>
  <enabled>yes</enabled>
  <index-status>yes</index-status>
  <feed-update-interval>yes</vulnerability_detection_feed_update_interval>
</vulnerability-detection>
# indexer configuration for vulnerability detection
<indexer>
  <enabled>yes</enabled>
  <hosts>
    <host>https://127.0.0.1:9200</host>
  </hosts>
  <username>admin</username>
  <password>admin</password>
  <ssl>
    <certificate_authorities>
      <ca>/etc/filebeat/certs/root-ca.pem</ca>
    </certificate_authorities>
    <certificate>/etc/filebeat/certs/filebeat.pem</certificate>
    <key>/etc/filebeat/certs/filebeat-key.pem</key>
  </ssl>
</indexer>
```


Distributed deployment

```
  # Configuration for Vulnerability detection
<vulnerability-detection>
  <enabled>yes</enabled>
  <index-status>yes</index-status>
  <feed-update-interval>yes</vulnerability_detection_feed_update_interval>
</vulnerability-detection>
# indexer configuration for vulnerability detection
<indexer>
  <enabled>yes</enabled>
  <hosts>
    <host>https://192.168.0.10:9200</host>
    <host>https://192.168.0.11:9200</host>
    <host>https://192.168.0.12:9200</host>
  </hosts>
  <username>admin</username>
  <password>admin</password>
  <ssl>
    <certificate_authorities>
      <ca>/etc/filebeat/certs/root-ca.pem</ca>
    </certificate_authorities>
    <certificate>/etc/filebeat/certs/filebeat.pem</certificate>
    <key>/etc/filebeat/certs/filebeat-key.pem</key>
  </ssl>
</indexer>
```
