### ISSUE TITLE
Wazuh service cannot be created in AL2023

### ISSUE THREAD

**Issue by lokasandeep** [wazuh/wazuh-puppet#902]
I am trying to install wazuh 4.7.1 on Al2023 AMI. getting the below error for the service resource type 

[1;31mError: /Stage[main]/Wazuh::Agent/Service[wazuh-agent]/ensure: change from 'stopped' to 'running' failed: Could not enable wazuh-agent: Execution of '/sbin/chkconfig --add wazuh-agent' returned 1: error reading information on service wazuh-agent: No such file or directory

we faced the same issue for other modules, but fixed it by updating the Provider as 'systemd' for service resource type. I could not find that in Wazuh module. please advice if any override parameters can be passed to Provider attribute. 

provider   => 'systemd',

**Comment by lokasandeep** [comment]
Puppet version: 6.13.0

**Comment by davidcr01** [comment]
Hello. Yes, this behavior is expected as our Puppet deployment didn't support the installation in Amazon Linux 2.

In the v4.8.0 Wazuh version, we added the support for Amazon Linux 2023 in the following PR: https://github.com/wazuh/wazuh-puppet/pull/1000
The v4.8.0 Wazuh version will be available in the next weeks. You can wait to this version to be released or use the 4.8.0 branch to perform this deployment, but take into account that this branch is in development currently.

Hope it helps.

**Comment by lokasandeep** [comment]
Thank you @davidcr01 for the update !.
