### ISSUE TITLE
Review compatibility with Puppet versions

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-puppet#92]

**Comment by LuisGi93** [comment]
Wazuh has been tested to be compatible with the following versions:

| Version      |End of life          | 
| ------------- |:-------------:| 
| Puppet 4.10.12     | December 31 2018| 
| Puppet 5       | May 2020   |   
| Puppet 6.1 | August 31 2019      |   

Wazuh throws errors in the following versions:

| Version      |End of life          | 
| ------------- |:-------------:| 
| Puppet 3.8.7 | December 31 2018     |

**Comment by jesuslinares** [comment]
Thanks @LuisGi93 !
