### ISSUE TITLE
Add Puppet 8 support

### ISSUE THREAD

**Issue by alexanderlebedev** [wazuh/wazuh-puppet#924]
Is it possible to add support for Puppet 8?

**Comment by davidcr01** [comment]
Hello. 

I have tested the Wazuh Puppet deployment using Puppet 8 and it worked perfectly for me. I followed this documentation: https://documentation.wazuh.com/current/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.html

Notice that you should change the Puppet version in the commands. For instance (DEB system), if you are installing the Puppet server package, make sure you change the `7` to an `8`:

```console
wget https://apt.puppet.com/puppet8-release-focal.deb
dpkg -i puppet8-release-focal.deb
apt-get update
apt-get install -y puppetserver
```
