### ISSUE TITLE
Delete all config about openscap

### ISSUE THREAD

**Issue by vcerenu** [wazuh/wazuh-puppet#999]
## Description

Openscap is deprecated, but we still have current configurations in our Puppet deployment.

You must proceed with the elimination of all the code related to the "open-scap" wodle configuration within the Wazuh manager and Wazuh agent deployment, since they have no real use.

Checking the code we can see that the variables to use Openscap are currently active:

https://github.com/wazuh/wazuh-puppet/blob/f4252b110301aa8914ad8e290ed293f35b9856e4/manifests/params_agent.pp#L31

https://github.com/wazuh/wazuh-puppet/blob/f4252b110301aa8914ad8e290ed293f35b9856e4/manifests/params_manager.pp#L37

Wazuh agents and managera still contain Openscap configurations when deployed:

https://github.com/wazuh/wazuh-puppet/blob/f4252b110301aa8914ad8e290ed293f35b9856e4/manifests/params_agent.pp#L366-L459

https://github.com/wazuh/wazuh-puppet/blob/f4252b110301aa8914ad8e290ed293f35b9856e4/manifests/params_manager.pp#L385-L517

Configurations are generated because the configure_wodle_openscap variable is in true state:

https://github.com/wazuh/wazuh-puppet/blob/f4252b110301aa8914ad8e290ed293f35b9856e4/manifests/agent.pp#L377-L385

https://github.com/wazuh/wazuh-puppet/blob/f4252b110301aa8914ad8e290ed293f35b9856e4/manifests/manager.pp#L467-L474

We should, in the first instance, remove the variables that enable this configuration and subsequently eliminate all the related code and templates.

**Comment by havidarou** [comment]
We will handle this as part of Legacy removal in Wazuh 5.0.0
